// GENERATED — do not edit by hand.
//
// Fixed catalogs are lifted verbatim from the `Guidelines` worksheet that the
// trusted ICEGrid output workbooks carry, so they cannot drift from the values the
// downstream ICEGATE upload actually accepts. Regenerating means re-reading that
// sheet, not retyping this file.
//
// Source workbook: tests/fixtures/icegrid/legacy/combined-xlsx/expected-output.xlsx
// sha256: a9d19f229403467cfa46da11d618b26d971c238bccaa102f3754ff6106518415
import type { IcegridCatalogOption, CatalogProvenance } from './types';

const freeze = (options: IcegridCatalogOption[]): readonly IcegridCatalogOption[] =>
	Object.freeze(options.map((o) => Object.freeze(o)));

export const GUIDELINES_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'workbook:tests/fixtures/icegrid/legacy/combined-xlsx/expected-output.xlsx#Guidelines',
	retrievedAt: '2026-08-29',
	sha256: "a9d19f229403467cfa46da11d618b26d971c238bccaa102f3754ff6106518415",
	entryCount: 188
});

/** Duplicate `RLS` in the source sheet is stored once. */
export const UNIT_OPTIONS = freeze([
	{ value: "BAG" },
	{ value: "BAL" },
	{ value: "BDL" },
	{ value: "BGS" },
	{ value: "BKL" },
	{ value: "BLK" },
	{ value: "BOU" },
	{ value: "BOX" },
	{ value: "BRL" },
	{ value: "BTL" },
	{ value: "BUN" },
	{ value: "CAN" },
	{ value: "CAS" },
	{ value: "CBM" },
	{ value: "CCM" },
	{ value: "CFT" },
	{ value: "CLS" },
	{ value: "CMS" },
	{ value: "COL" },
	{ value: "CON" },
	{ value: "CRT" },
	{ value: "CSK" },
	{ value: "CTM" },
	{ value: "CTN" },
	{ value: "DOZ" },
	{ value: "DRM" },
	{ value: "FTS" },
	{ value: "GGR" },
	{ value: "GMS" },
	{ value: "GRS" },
	{ value: "GYD" },
	{ value: "JRS" },
	{ value: "KGS" },
	{ value: "KIT" },
	{ value: "KLR" },
	{ value: "KME" },
	{ value: "LBS" },
	{ value: "LOT" },
	{ value: "LTR" },
	{ value: "MGS" },
	{ value: "MLT" },
	{ value: "MOU" },
	{ value: "MTR" },
	{ value: "MTS" },
	{ value: "NOS" },
	{ value: "PAC" },
	{ value: "PCS" },
	{ value: "PKG" },
	{ value: "PLT" },
	{ value: "PRS" },
	{ value: "QTL" },
	{ value: "RLS" },
	{ value: "ROL" },
	{ value: "SAC" },
	{ value: "SET" },
	{ value: "SHT" },
	{ value: "SLB" },
	{ value: "SQF" },
	{ value: "SQM" },
	{ value: "SQY" },
	{ value: "TBS" },
	{ value: "TGM" },
	{ value: "THD" },
	{ value: "TIN" },
	{ value: "TON" },
	{ value: "TUB" },
	{ value: "UGS" },
	{ value: "UNT" },
	{ value: "VLS" },
	{ value: "YDS" }
]);

/**
 * Complete canonical scheme values. Codes 36 and 56 each have two distinct
 * descriptions and are deliberately kept as separate entries; a bare 36 or 56 is
 * therefore ambiguous and must not auto-resolve.
 */
export const SCHEME_OPTIONS = freeze([
	{ value: "00-Free Shipping bill " },
	{ value: "01-Advance Licence with actual user condition" },
	{ value: "02-Advance licence for intermediate supplies" },
	{ value: "03-Advance licence" },
	{ value: "04-Advance Release order" },
	{ value: "05-Advance Licence for deemed exports" },
	{ value: "06-DEPB-post exports" },
	{ value: "07-DEPB-pre exports" },
	{ value: "08-Replenishment licence" },
	{ value: "09-Diamond imprest licence" },
	{ value: "10-Bulk licence" },
	{ value: "11-Concessional duty EPCG scheme" },
	{ value: "12-Zero duty EPCG scheme" },
	{ value: "13-CCP" },
	{ value: "14-Import License For Restricted Items Of Imports" },
	{ value: "15-Special Import licence" },
	{ value: "16-Export licence" },
	{ value: "17-Advance Licence for annual requirement" },
	{ value: "18-Duty Free Replenishment Certificate" },
	{ value: "19-Drawback (DBK)" },
	{ value: "20-Jobbing (JBG)" },
	{ value: "21-EOU/EPZ/SEZ/EHTP/STP" },
	{ value: "22-SERVED FROM INDIA SCHEME" },
	{ value: "23-Target Plus Scheme" },
	{ value: "24-Vishesh Krishi Upaj Yojana" },
	{ value: "25-DFCE for Status Holder" },
	{ value: "26-Duty Free Import Authorisation" },
	{ value: "27-Focus Market Scheme" },
	{ value: "28-Focus Product Scheme" },
	{ value: "29-High-Tech Products Export Promotion Scheme" },
	{ value: "30-EPCG Duty Based" },
	{ value: "31-Status Holder Incentive Scheme" },
	{ value: "35-Incremental Incentivisation Scheme" },
	{ value: "36-MEIS" },
	{ value: "36-Merchandise Export Incentive Scheme" },
	{ value: "37-Service Export Incentive Scheme" },
	{ value: "40-DBK and Advance Licence for annual requirement" },
	{ value: "41-Drawback and Advance Licence" },
	{ value: "42-Drawback and DFRC" },
	{ value: "43-Drawback and zero duty EPCG" },
	{ value: "44-Drawback and concessional duty EPCG" },
	{ value: "45-Drawback and Pre export DEPB" },
	{ value: "46-Drawback and post export DEPB" },
	{ value: "47-Drawback and JBG" },
	{ value: "48-Drawback and Diamond Imprest licence" },
	{ value: "49-Drawback and EOU/EPZ/SEZ" },
	{ value: "50-EPCG and Advance licence" },
	{ value: "51-EPCG and DFRC" },
	{ value: "52-EPCG and JBG" },
	{ value: "53-EPCG and Diamond imprest Licence" },
	{ value: "54-EPCG and Replenishment Licences" },
	{ value: "55-EPCG and DEPB (Post exports)" },
	{ value: "56-EPCG and Advance Licence for annual requirement" },
	{ value: "56-EPCG and DEPB (Pre-exports)" },
	{ value: "59-EPCG AND DFIA" },
	{ value: "60-Drawback and Rebate of State Levies" },
	{ value: "61-EPCG,Drawback and Rebate of State Levies" },
	{ value: "62-Drawback and special DEEC(4.04A)" },
	{ value: "63-EPCG,Drawback and special DEEC(4.04A)" },
	{ value: "64-Drawback,special DEEC(4.04A) and Rebate of State Levis" },
	{ value: "65-EPCG,Drawback \"&\" special DEEC(4.04A) and Rebate of State Levis" },
	{ value: "71-EPCG, DRAWBACK AND DEEC" },
	{ value: "72-EPCG, DRAWBACK AND DFRC" },
	{ value: "73-EPCG, DRAWBACK AND JOBBING" },
	{ value: "74-EPCG, DRAWBACK AND DIAMOND IMPREST LICENCE" },
	{ value: "75-EPCG, DRAWBACK AND DEPB POST EXPORT" },
	{ value: "79-EPCG, DRAWBACK AND DFIA" },
	{ value: "98-Free Shipping Bill involving Indian Currency" },
	{ value: "99-NFEI" }
]);

/** Duplicate `FSH700` in the source sheet is stored once. */
export const END_USE_OPTIONS = freeze([
	{ value: "DCA100" },
	{ value: "DCH100" },
	{ value: "DCH300" },
	{ value: "DCH400" },
	{ value: "DCH800" },
	{ value: "DCX200" },
	{ value: "DCX900" },
	{ value: "FSA100" },
	{ value: "FSA200" },
	{ value: "FSA800" },
	{ value: "FSA900" },
	{ value: "FSH100" },
	{ value: "FSH200" },
	{ value: "FSH700" },
	{ value: "FSH750" },
	{ value: "FSH800" },
	{ value: "FSH900" },
	{ value: "FSH910" },
	{ value: "FSH920" },
	{ value: "FSH930" },
	{ value: "GNX100" },
	{ value: "GNX200" },
	{ value: "GNX300" },
	{ value: "GNX600" },
	{ value: "GNX650" },
	{ value: "GNX680" },
	{ value: "GNX700" },
	{ value: "GNX810" },
	{ value: "GNX815" },
	{ value: "GNX915" },
	{ value: "LVA100" },
	{ value: "LVA200" },
	{ value: "LVA300" },
	{ value: "LVA400" },
	{ value: "LVA500" },
	{ value: "LVA710" },
	{ value: "LVA760" },
	{ value: "LVA800" },
	{ value: "LVA900" },
	{ value: "LVA950" },
	{ value: "LVP100" },
	{ value: "LVP400" },
	{ value: "LVP500" },
	{ value: "LVP730" }
]);

export const IGST_PAYMENT_STATUS_OPTIONS = freeze([
	{ value: "NA" },
	{ value: "LUT" },
	{ value: "P" }
]);

export const REWARD_ITEM_OPTIONS = freeze([
	{ value: "Yes" },
	{ value: "No" }
]);

/** RODTEP additionally allows `N/A`, which the Guidelines Yes/No column omits. */
export const RODTEP_OPTIONS = freeze([
	{ value: "Yes" },
	{ value: "No" },
	{ value: "N/A" }
]);

export const COUNTRY_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'iso:3166-1-alpha-2',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 274
});

/** ISO 3166-1 alpha-2. Stored/exported as the two-letter code; the name is display only. */
export const COUNTRY_OPTIONS = freeze([
	{ value: "AC", label: "ASCENSION ISLAND" },
	{ value: "AD", label: "ANDORRA" },
	{ value: "AE", label: "UNITED ARAB EMIRATES" },
	{ value: "AF", label: "AFGHANISTAN" },
	{ value: "AG", label: "ANTIGUA & BARBUDA" },
	{ value: "AI", label: "ANGUILLA" },
	{ value: "AL", label: "ALBANIA" },
	{ value: "AM", label: "ARMENIA" },
	{ value: "AN", label: "CURAÇAO" },
	{ value: "AO", label: "ANGOLA" },
	{ value: "AQ", label: "ANTARCTICA" },
	{ value: "AR", label: "ARGENTINA" },
	{ value: "AS", label: "AMERICAN SAMOA" },
	{ value: "AT", label: "AUSTRIA" },
	{ value: "AU", label: "AUSTRALIA" },
	{ value: "AW", label: "ARUBA" },
	{ value: "AX", label: "ÅLAND ISLANDS" },
	{ value: "AZ", label: "AZERBAIJAN" },
	{ value: "BA", label: "BOSNIA & HERZEGOVINA" },
	{ value: "BB", label: "BARBADOS" },
	{ value: "BD", label: "BANGLADESH" },
	{ value: "BE", label: "BELGIUM" },
	{ value: "BF", label: "BURKINA FASO" },
	{ value: "BG", label: "BULGARIA" },
	{ value: "BH", label: "BAHRAIN" },
	{ value: "BI", label: "BURUNDI" },
	{ value: "BJ", label: "BENIN" },
	{ value: "BL", label: "ST. BARTHÉLEMY" },
	{ value: "BM", label: "BERMUDA" },
	{ value: "BN", label: "BRUNEI" },
	{ value: "BO", label: "BOLIVIA" },
	{ value: "BQ", label: "CARIBBEAN NETHERLANDS" },
	{ value: "BR", label: "BRAZIL" },
	{ value: "BS", label: "BAHAMAS" },
	{ value: "BT", label: "BHUTAN" },
	{ value: "BU", label: "MYANMAR (BURMA)" },
	{ value: "BV", label: "BOUVET ISLAND" },
	{ value: "BW", label: "BOTSWANA" },
	{ value: "BY", label: "BELARUS" },
	{ value: "BZ", label: "BELIZE" },
	{ value: "CA", label: "CANADA" },
	{ value: "CC", label: "COCOS (KEELING) ISLANDS" },
	{ value: "CD", label: "CONGO - KINSHASA" },
	{ value: "CF", label: "CENTRAL AFRICAN REPUBLIC" },
	{ value: "CG", label: "CONGO - BRAZZAVILLE" },
	{ value: "CH", label: "SWITZERLAND" },
	{ value: "CI", label: "CÔTE D’IVOIRE" },
	{ value: "CK", label: "COOK ISLANDS" },
	{ value: "CL", label: "CHILE" },
	{ value: "CM", label: "CAMEROON" },
	{ value: "CN", label: "CHINA" },
	{ value: "CO", label: "COLOMBIA" },
	{ value: "CP", label: "CLIPPERTON ISLAND" },
	{ value: "CQ", label: "SARK" },
	{ value: "CR", label: "COSTA RICA" },
	{ value: "CS", label: "SERBIA" },
	{ value: "CU", label: "CUBA" },
	{ value: "CV", label: "CAPE VERDE" },
	{ value: "CW", label: "CURAÇAO" },
	{ value: "CX", label: "CHRISTMAS ISLAND" },
	{ value: "CY", label: "CYPRUS" },
	{ value: "CZ", label: "CZECHIA" },
	{ value: "DD", label: "GERMANY" },
	{ value: "DE", label: "GERMANY" },
	{ value: "DG", label: "DIEGO GARCIA" },
	{ value: "DJ", label: "DJIBOUTI" },
	{ value: "DK", label: "DENMARK" },
	{ value: "DM", label: "DOMINICA" },
	{ value: "DO", label: "DOMINICAN REPUBLIC" },
	{ value: "DY", label: "BENIN" },
	{ value: "DZ", label: "ALGERIA" },
	{ value: "EA", label: "CEUTA & MELILLA" },
	{ value: "EC", label: "ECUADOR" },
	{ value: "EE", label: "ESTONIA" },
	{ value: "EG", label: "EGYPT" },
	{ value: "EH", label: "WESTERN SAHARA" },
	{ value: "ER", label: "ERITREA" },
	{ value: "ES", label: "SPAIN" },
	{ value: "ET", label: "ETHIOPIA" },
	{ value: "EZ", label: "EUROZONE" },
	{ value: "FI", label: "FINLAND" },
	{ value: "FJ", label: "FIJI" },
	{ value: "FK", label: "FALKLAND ISLANDS" },
	{ value: "FM", label: "MICRONESIA" },
	{ value: "FO", label: "FAROE ISLANDS" },
	{ value: "FR", label: "FRANCE" },
	{ value: "FX", label: "FRANCE" },
	{ value: "GA", label: "GABON" },
	{ value: "GB", label: "UNITED KINGDOM" },
	{ value: "GD", label: "GRENADA" },
	{ value: "GE", label: "GEORGIA" },
	{ value: "GF", label: "FRENCH GUIANA" },
	{ value: "GG", label: "GUERNSEY" },
	{ value: "GH", label: "GHANA" },
	{ value: "GI", label: "GIBRALTAR" },
	{ value: "GL", label: "GREENLAND" },
	{ value: "GM", label: "GAMBIA" },
	{ value: "GN", label: "GUINEA" },
	{ value: "GP", label: "GUADELOUPE" },
	{ value: "GQ", label: "EQUATORIAL GUINEA" },
	{ value: "GR", label: "GREECE" },
	{ value: "GS", label: "SOUTH GEORGIA & SOUTH SANDWICH ISLANDS" },
	{ value: "GT", label: "GUATEMALA" },
	{ value: "GU", label: "GUAM" },
	{ value: "GW", label: "GUINEA-BISSAU" },
	{ value: "GY", label: "GUYANA" },
	{ value: "HK", label: "HONG KONG SAR CHINA" },
	{ value: "HM", label: "HEARD & MCDONALD ISLANDS" },
	{ value: "HN", label: "HONDURAS" },
	{ value: "HR", label: "CROATIA" },
	{ value: "HT", label: "HAITI" },
	{ value: "HU", label: "HUNGARY" },
	{ value: "HV", label: "BURKINA FASO" },
	{ value: "IC", label: "CANARY ISLANDS" },
	{ value: "ID", label: "INDONESIA" },
	{ value: "IE", label: "IRELAND" },
	{ value: "IL", label: "ISRAEL" },
	{ value: "IM", label: "ISLE OF MAN" },
	{ value: "IN", label: "INDIA" },
	{ value: "IO", label: "BRITISH INDIAN OCEAN TERRITORY" },
	{ value: "IQ", label: "IRAQ" },
	{ value: "IR", label: "IRAN" },
	{ value: "IS", label: "ICELAND" },
	{ value: "IT", label: "ITALY" },
	{ value: "JE", label: "JERSEY" },
	{ value: "JM", label: "JAMAICA" },
	{ value: "JO", label: "JORDAN" },
	{ value: "JP", label: "JAPAN" },
	{ value: "KE", label: "KENYA" },
	{ value: "KG", label: "KYRGYZSTAN" },
	{ value: "KH", label: "CAMBODIA" },
	{ value: "KI", label: "KIRIBATI" },
	{ value: "KM", label: "COMOROS" },
	{ value: "KN", label: "ST. KITTS & NEVIS" },
	{ value: "KP", label: "NORTH KOREA" },
	{ value: "KR", label: "SOUTH KOREA" },
	{ value: "KW", label: "KUWAIT" },
	{ value: "KY", label: "CAYMAN ISLANDS" },
	{ value: "KZ", label: "KAZAKHSTAN" },
	{ value: "LA", label: "LAOS" },
	{ value: "LB", label: "LEBANON" },
	{ value: "LC", label: "ST. LUCIA" },
	{ value: "LI", label: "LIECHTENSTEIN" },
	{ value: "LK", label: "SRI LANKA" },
	{ value: "LR", label: "LIBERIA" },
	{ value: "LS", label: "LESOTHO" },
	{ value: "LT", label: "LITHUANIA" },
	{ value: "LU", label: "LUXEMBOURG" },
	{ value: "LV", label: "LATVIA" },
	{ value: "LY", label: "LIBYA" },
	{ value: "MA", label: "MOROCCO" },
	{ value: "MC", label: "MONACO" },
	{ value: "MD", label: "MOLDOVA" },
	{ value: "ME", label: "MONTENEGRO" },
	{ value: "MF", label: "ST. MARTIN" },
	{ value: "MG", label: "MADAGASCAR" },
	{ value: "MH", label: "MARSHALL ISLANDS" },
	{ value: "MK", label: "NORTH MACEDONIA" },
	{ value: "ML", label: "MALI" },
	{ value: "MM", label: "MYANMAR (BURMA)" },
	{ value: "MN", label: "MONGOLIA" },
	{ value: "MO", label: "MACAO SAR CHINA" },
	{ value: "MP", label: "NORTHERN MARIANA ISLANDS" },
	{ value: "MQ", label: "MARTINIQUE" },
	{ value: "MR", label: "MAURITANIA" },
	{ value: "MS", label: "MONTSERRAT" },
	{ value: "MT", label: "MALTA" },
	{ value: "MU", label: "MAURITIUS" },
	{ value: "MV", label: "MALDIVES" },
	{ value: "MW", label: "MALAWI" },
	{ value: "MX", label: "MEXICO" },
	{ value: "MY", label: "MALAYSIA" },
	{ value: "MZ", label: "MOZAMBIQUE" },
	{ value: "NA", label: "NAMIBIA" },
	{ value: "NC", label: "NEW CALEDONIA" },
	{ value: "NE", label: "NIGER" },
	{ value: "NF", label: "NORFOLK ISLAND" },
	{ value: "NG", label: "NIGERIA" },
	{ value: "NH", label: "VANUATU" },
	{ value: "NI", label: "NICARAGUA" },
	{ value: "NL", label: "NETHERLANDS" },
	{ value: "NO", label: "NORWAY" },
	{ value: "NP", label: "NEPAL" },
	{ value: "NR", label: "NAURU" },
	{ value: "NU", label: "NIUE" },
	{ value: "NZ", label: "NEW ZEALAND" },
	{ value: "OM", label: "OMAN" },
	{ value: "PA", label: "PANAMA" },
	{ value: "PE", label: "PERU" },
	{ value: "PF", label: "FRENCH POLYNESIA" },
	{ value: "PG", label: "PAPUA NEW GUINEA" },
	{ value: "PH", label: "PHILIPPINES" },
	{ value: "PK", label: "PAKISTAN" },
	{ value: "PL", label: "POLAND" },
	{ value: "PM", label: "ST. PIERRE & MIQUELON" },
	{ value: "PN", label: "PITCAIRN ISLANDS" },
	{ value: "PR", label: "PUERTO RICO" },
	{ value: "PS", label: "PALESTINIAN TERRITORIES" },
	{ value: "PT", label: "PORTUGAL" },
	{ value: "PW", label: "PALAU" },
	{ value: "PY", label: "PARAGUAY" },
	{ value: "QA", label: "QATAR" },
	{ value: "RE", label: "RÉUNION" },
	{ value: "RH", label: "ZIMBABWE" },
	{ value: "RO", label: "ROMANIA" },
	{ value: "RS", label: "SERBIA" },
	{ value: "RU", label: "RUSSIA" },
	{ value: "RW", label: "RWANDA" },
	{ value: "SA", label: "SAUDI ARABIA" },
	{ value: "SB", label: "SOLOMON ISLANDS" },
	{ value: "SC", label: "SEYCHELLES" },
	{ value: "SD", label: "SUDAN" },
	{ value: "SE", label: "SWEDEN" },
	{ value: "SG", label: "SINGAPORE" },
	{ value: "SH", label: "ST. HELENA" },
	{ value: "SI", label: "SLOVENIA" },
	{ value: "SJ", label: "SVALBARD & JAN MAYEN" },
	{ value: "SK", label: "SLOVAKIA" },
	{ value: "SL", label: "SIERRA LEONE" },
	{ value: "SM", label: "SAN MARINO" },
	{ value: "SN", label: "SENEGAL" },
	{ value: "SO", label: "SOMALIA" },
	{ value: "SR", label: "SURINAME" },
	{ value: "SS", label: "SOUTH SUDAN" },
	{ value: "ST", label: "SÃO TOMÉ & PRÍNCIPE" },
	{ value: "SU", label: "RUSSIA" },
	{ value: "SV", label: "EL SALVADOR" },
	{ value: "SX", label: "SINT MAARTEN" },
	{ value: "SY", label: "SYRIA" },
	{ value: "SZ", label: "ESWATINI" },
	{ value: "TA", label: "TRISTAN DA CUNHA" },
	{ value: "TC", label: "TURKS & CAICOS ISLANDS" },
	{ value: "TD", label: "CHAD" },
	{ value: "TF", label: "FRENCH SOUTHERN TERRITORIES" },
	{ value: "TG", label: "TOGO" },
	{ value: "TH", label: "THAILAND" },
	{ value: "TJ", label: "TAJIKISTAN" },
	{ value: "TK", label: "TOKELAU" },
	{ value: "TL", label: "TIMOR-LESTE" },
	{ value: "TM", label: "TURKMENISTAN" },
	{ value: "TN", label: "TUNISIA" },
	{ value: "TO", label: "TONGA" },
	{ value: "TP", label: "TIMOR-LESTE" },
	{ value: "TR", label: "TÜRKIYE" },
	{ value: "TT", label: "TRINIDAD & TOBAGO" },
	{ value: "TV", label: "TUVALU" },
	{ value: "TW", label: "TAIWAN" },
	{ value: "TZ", label: "TANZANIA" },
	{ value: "UA", label: "UKRAINE" },
	{ value: "UG", label: "UGANDA" },
	{ value: "UK", label: "UNITED KINGDOM" },
	{ value: "UM", label: "U.S. OUTLYING ISLANDS" },
	{ value: "US", label: "UNITED STATES" },
	{ value: "UY", label: "URUGUAY" },
	{ value: "UZ", label: "UZBEKISTAN" },
	{ value: "VA", label: "VATICAN CITY" },
	{ value: "VC", label: "ST. VINCENT & GRENADINES" },
	{ value: "VD", label: "VIETNAM" },
	{ value: "VE", label: "VENEZUELA" },
	{ value: "VG", label: "BRITISH VIRGIN ISLANDS" },
	{ value: "VI", label: "U.S. VIRGIN ISLANDS" },
	{ value: "VN", label: "VIETNAM" },
	{ value: "VU", label: "VANUATU" },
	{ value: "WF", label: "WALLIS & FUTUNA" },
	{ value: "WS", label: "SAMOA" },
	{ value: "XK", label: "KOSOVO" },
	{ value: "YD", label: "YEMEN" },
	{ value: "YE", label: "YEMEN" },
	{ value: "YT", label: "MAYOTTE" },
	{ value: "YU", label: "SERBIA" },
	{ value: "ZA", label: "SOUTH AFRICA" },
	{ value: "ZM", label: "ZAMBIA" },
	{ value: "ZR", label: "CONGO - KINSHASA" },
	{ value: "ZW", label: "ZIMBABWE" }
]);

export const STATE_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'https://www.icegate.gov.in/Webappl/state_det_all.jsp',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 40
});

/** Two-digit GST/ICEGATE state codes. Leading zeroes are significant. */
export const STATE_OPTIONS = freeze([
	{ value: "01", label: "JAMMU AND KASHMIR" },
	{ value: "02", label: "HIMACHAL PRADESH" },
	{ value: "03", label: "PUNJAB" },
	{ value: "04", label: "CHANDIGARH" },
	{ value: "05", label: "UTTARAKHAND" },
	{ value: "06", label: "HARYANA" },
	{ value: "07", label: "DELHI" },
	{ value: "08", label: "RAJASTHAN" },
	{ value: "09", label: "UTTAR PRADESH" },
	{ value: "10", label: "BIHAR" },
	{ value: "11", label: "SIKKIM" },
	{ value: "12", label: "ARUNACHAL PRADESH" },
	{ value: "13", label: "NAGALAND" },
	{ value: "14", label: "MANIPUR" },
	{ value: "15", label: "MIZORAM" },
	{ value: "16", label: "TRIPURA" },
	{ value: "17", label: "MEGHALAYA" },
	{ value: "18", label: "ASSAM" },
	{ value: "19", label: "WEST BENGAL" },
	{ value: "20", label: "JHARKHAND" },
	{ value: "21", label: "ODISHA" },
	{ value: "22", label: "CHHATTISGARH" },
	{ value: "23", label: "MADHYA PRADESH" },
	{ value: "24", label: "GUJARAT" },
	{ value: "25", label: "DAMAN AND DIU" },
	{ value: "26", label: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU" },
	{ value: "27", label: "MAHARASHTRA" },
	{ value: "28", label: "ANDHRA PRADESH" },
	{ value: "29", label: "KARNATAKA" },
	{ value: "30", label: "GOA" },
	{ value: "31", label: "LAKSHADWEEP" },
	{ value: "32", label: "KERALA" },
	{ value: "33", label: "TAMIL NADU" },
	{ value: "34", label: "PUDUCHERRY" },
	{ value: "35", label: "ANDAMAN AND NICOBAR ISLANDS" },
	{ value: "36", label: "TELANGANA" },
	{ value: "37", label: "ANDHRA PRADESH (NEW)" },
	{ value: "38", label: "LADAKH" },
	{ value: "97", label: "OTHER TERRITORY" },
	{ value: "99", label: "CENTRE JURISDICTION" }
]);

export const FTA_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'https://www.icegate.gov.in/Webappl/Ftp',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 21
});

export const FTA_OPTIONS = freeze([
	{ value: "FTA0SL" },
	{ value: "FTA0SA" },
	{ value: "FTA0NL" },
	{ value: "FTA0BT" },
	{ value: "FTA0TH" },
	{ value: "CEPASG" },
	{ value: "CEPASEA" },
	{ value: "CEPAKR" },
	{ value: "CEPAJP" },
	{ value: "CECAMY" },
	{ value: "PTAAPTA" },
	{ value: "GSTP" },
	{ value: "PTA0SA" },
	{ value: "PTA0AF" },
	{ value: "PTA0MER" },
	{ value: "PTA0CL" },
	{ value: "NCPTI" },
	{ value: "ECTAAU" },
	{ value: "CEPAOM" },
	{ value: "CEPAAE" },
	{ value: "CETAUK" }
]);

/**
 * No official ICEGATE district export was available, so there are no built-in
 * districts. The column stays a state-dependent dropdown with `allowCustom`, which
 * means a district is only ever present because a user typed it — never guessed.
 */
export const DISTRICT_OPTIONS = freeze([]);
