// GENERATED — do not edit by hand.
//
// Fixed catalogs are lifted verbatim from the `Guidelines` worksheet that the
// trusted ICEGrid output workbooks carry, so they cannot drift from the values the
// downstream ICEGATE upload actually accepts. Regenerating means re-reading that
// sheet, not retyping this file.
//
// Source workbook: tests/icegrid/fixtures/01-split-xls-igst-paid/expected-output.xlsx
// sha256: 8cfb8bef404a62aa356ab9d35d8ce3a1d5698101830f4dbf5bd53a14eb8f49ee
import type { IcegridCatalogOption, CatalogProvenance } from './types';

const freeze = (options: IcegridCatalogOption[]): readonly IcegridCatalogOption[] =>
	Object.freeze(options.map((o) => Object.freeze(o)));

export const GUIDELINES_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'workbook:tests/icegrid/fixtures/01-split-xls-igst-paid/expected-output.xlsx#Guidelines',
	retrievedAt: '2026-08-29',
	sha256: "8cfb8bef404a62aa356ab9d35d8ce3a1d5698101830f4dbf5bd53a14eb8f49ee",
	entryCount: 188
});

/** Duplicate `RLS` in the source sheet is stored once. */
export const UNIT_OPTIONS = freeze([
	{ value: "BAG" },
	{ value: "BAL" },
	{ value: "BDL" },
	{ value: "BGS" },
	{ value: "BKL" },
	{ value: "BLK" },
	{ value: "BOU" },
	{ value: "BOX" },
	{ value: "BRL" },
	{ value: "BTL" },
	{ value: "BUN" },
	{ value: "CAN" },
	{ value: "CAS" },
	{ value: "CBM" },
	{ value: "CCM" },
	{ value: "CFT" },
	{ value: "CLS" },
	{ value: "CMS" },
	{ value: "COL" },
	{ value: "CON" },
	{ value: "CRT" },
	{ value: "CSK" },
	{ value: "CTM" },
	{ value: "CTN" },
	{ value: "DOZ" },
	{ value: "DRM" },
	{ value: "FTS" },
	{ value: "GGR" },
	{ value: "GMS" },
	{ value: "GRS" },
	{ value: "GYD" },
	{ value: "JRS" },
	{ value: "KGS" },
	{ value: "KIT" },
	{ value: "KLR" },
	{ value: "KME" },
	{ value: "LBS" },
	{ value: "LOT" },
	{ value: "LTR" },
	{ value: "MGS" },
	{ value: "MLT" },
	{ value: "MOU" },
	{ value: "MTR" },
	{ value: "MTS" },
	{ value: "NOS" },
	{ value: "PAC" },
	{ value: "PCS" },
	{ value: "PKG" },
	{ value: "PLT" },
	{ value: "PRS" },
	{ value: "QTL" },
	{ value: "RLS" },
	{ value: "ROL" },
	{ value: "SAC" },
	{ value: "SET" },
	{ value: "SHT" },
	{ value: "SLB" },
	{ value: "SQF" },
	{ value: "SQM" },
	{ value: "SQY" },
	{ value: "TBS" },
	{ value: "TGM" },
	{ value: "THD" },
	{ value: "TIN" },
	{ value: "TON" },
	{ value: "TUB" },
	{ value: "UGS" },
	{ value: "UNT" },
	{ value: "VLS" },
	{ value: "YDS" }
]);

/**
 * Complete canonical scheme values. Codes 36 and 56 each have two distinct
 * descriptions and are deliberately kept as separate entries; a bare 36 or 56 is
 * therefore ambiguous and must not auto-resolve.
 */
export const SCHEME_OPTIONS = freeze([
	{ value: "00-Free Shipping bill " },
	{ value: "01-Advance Licence with actual user condition" },
	{ value: "02-Advance licence for intermediate supplies" },
	{ value: "03-Advance licence" },
	{ value: "04-Advance Release order" },
	{ value: "05-Advance Licence for deemed exports" },
	{ value: "06-DEPB-post exports" },
	{ value: "07-DEPB-pre exports" },
	{ value: "08-Replenishment licence" },
	{ value: "09-Diamond imprest licence" },
	{ value: "10-Bulk licence" },
	{ value: "11-Concessional duty EPCG scheme" },
	{ value: "12-Zero duty EPCG scheme" },
	{ value: "13-CCP" },
	{ value: "14-Import License For Restricted Items Of Imports" },
	{ value: "15-Special Import licence" },
	{ value: "16-Export licence" },
	{ value: "17-Advance Licence for annual requirement" },
	{ value: "18-Duty Free Replenishment Certificate" },
	{ value: "19-Drawback (DBK)" },
	{ value: "20-Jobbing (JBG)" },
	{ value: "21-EOU/EPZ/SEZ/EHTP/STP" },
	{ value: "22-SERVED FROM INDIA SCHEME" },
	{ value: "23-Target Plus Scheme" },
	{ value: "24-Vishesh Krishi Upaj Yojana" },
	{ value: "25-DFCE for Status Holder" },
	{ value: "26-Duty Free Import Authorisation" },
	{ value: "27-Focus Market Scheme" },
	{ value: "28-Focus Product Scheme" },
	{ value: "29-High-Tech Products Export Promotion Scheme" },
	{ value: "30-EPCG Duty Based" },
	{ value: "31-Status Holder Incentive Scheme" },
	{ value: "35-Incremental Incentivisation Scheme" },
	{ value: "36-MEIS" },
	{ value: "36-Merchandise Export Incentive Scheme" },
	{ value: "37-Service Export Incentive Scheme" },
	{ value: "40-DBK and Advance Licence for annual requirement" },
	{ value: "41-Drawback and Advance Licence" },
	{ value: "42-Drawback and DFRC" },
	{ value: "43-Drawback and zero duty EPCG" },
	{ value: "44-Drawback and concessional duty EPCG" },
	{ value: "45-Drawback and Pre export DEPB" },
	{ value: "46-Drawback and post export DEPB" },
	{ value: "47-Drawback and JBG" },
	{ value: "48-Drawback and Diamond Imprest licence" },
	{ value: "49-Drawback and EOU/EPZ/SEZ" },
	{ value: "50-EPCG and Advance licence" },
	{ value: "51-EPCG and DFRC" },
	{ value: "52-EPCG and JBG" },
	{ value: "53-EPCG and Diamond imprest Licence" },
	{ value: "54-EPCG and Replenishment Licences" },
	{ value: "55-EPCG and DEPB (Post exports)" },
	{ value: "56-EPCG and Advance Licence for annual requirement" },
	{ value: "56-EPCG and DEPB (Pre-exports)" },
	{ value: "59-EPCG AND DFIA" },
	{ value: "60-Drawback and Rebate of State Levies" },
	{ value: "61-EPCG,Drawback and Rebate of State Levies" },
	{ value: "62-Drawback and special DEEC(4.04A)" },
	{ value: "63-EPCG,Drawback and special DEEC(4.04A)" },
	{ value: "64-Drawback,special DEEC(4.04A) and Rebate of State Levis" },
	{ value: "65-EPCG,Drawback \"&\" special DEEC(4.04A) and Rebate of State Levis" },
	{ value: "71-EPCG, DRAWBACK AND DEEC" },
	{ value: "72-EPCG, DRAWBACK AND DFRC" },
	{ value: "73-EPCG, DRAWBACK AND JOBBING" },
	{ value: "74-EPCG, DRAWBACK AND DIAMOND IMPREST LICENCE" },
	{ value: "75-EPCG, DRAWBACK AND DEPB POST EXPORT" },
	{ value: "79-EPCG, DRAWBACK AND DFIA" },
	{ value: "98-Free Shipping Bill involving Indian Currency" },
	{ value: "99-NFEI" }
]);

/** Duplicate `FSH700` in the source sheet is stored once. */
export const END_USE_OPTIONS = freeze([
	{ value: "DCA100" },
	{ value: "DCH100" },
	{ value: "DCH300" },
	{ value: "DCH400" },
	{ value: "DCH800" },
	{ value: "DCX200" },
	{ value: "DCX900" },
	{ value: "FSA100" },
	{ value: "FSA200" },
	{ value: "FSA800" },
	{ value: "FSA900" },
	{ value: "FSH100" },
	{ value: "FSH200" },
	{ value: "FSH700" },
	{ value: "FSH750" },
	{ value: "FSH800" },
	{ value: "FSH900" },
	{ value: "FSH910" },
	{ value: "FSH920" },
	{ value: "FSH930" },
	{ value: "GNX100" },
	{ value: "GNX200" },
	{ value: "GNX300" },
	{ value: "GNX600" },
	{ value: "GNX650" },
	{ value: "GNX680" },
	{ value: "GNX700" },
	{ value: "GNX810" },
	{ value: "GNX815" },
	{ value: "GNX915" },
	{ value: "LVA100" },
	{ value: "LVA200" },
	{ value: "LVA300" },
	{ value: "LVA400" },
	{ value: "LVA500" },
	{ value: "LVA710" },
	{ value: "LVA760" },
	{ value: "LVA800" },
	{ value: "LVA900" },
	{ value: "LVA950" },
	{ value: "LVP100" },
	{ value: "LVP400" },
	{ value: "LVP500" },
	{ value: "LVP730" }
]);

export const IGST_PAYMENT_STATUS_OPTIONS = freeze([
	{ value: "NA" },
	{ value: "LUT" },
	{ value: "P" }
]);

export const REWARD_ITEM_OPTIONS = freeze([
	{ value: "Yes" },
	{ value: "No" }
]);

/** RODTEP additionally allows `N/A`, which the Guidelines Yes/No column omits. */
export const RODTEP_OPTIONS = freeze([
	{ value: "Yes" },
	{ value: "No" },
	{ value: "N/A" }
]);

export const COUNTRY_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'iso:3166-1-alpha-2',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 274
});

/** ISO 3166-1 alpha-2. Stored/exported as the two-letter code; the name is display only. */
export const COUNTRY_OPTIONS = freeze([
	{ value: "AC", label: "ASCENSION ISLAND" },
	{ value: "AD", label: "ANDORRA" },
	{ value: "AE", label: "UNITED ARAB EMIRATES" },
	{ value: "AF", label: "AFGHANISTAN" },
	{ value: "AG", label: "ANTIGUA & BARBUDA" },
	{ value: "AI", label: "ANGUILLA" },
	{ value: "AL", label: "ALBANIA" },
	{ value: "AM", label: "ARMENIA" },
	{ value: "AN", label: "CURAÇAO" },
	{ value: "AO", label: "ANGOLA" },
	{ value: "AQ", label: "ANTARCTICA" },
	{ value: "AR", label: "ARGENTINA" },
	{ value: "AS", label: "AMERICAN SAMOA" },
	{ value: "AT", label: "AUSTRIA" },
	{ value: "AU", label: "AUSTRALIA" },
	{ value: "AW", label: "ARUBA" },
	{ value: "AX", label: "ÅLAND ISLANDS" },
	{ value: "AZ", label: "AZERBAIJAN" },
	{ value: "BA", label: "BOSNIA & HERZEGOVINA" },
	{ value: "BB", label: "BARBADOS" },
	{ value: "BD", label: "BANGLADESH" },
	{ value: "BE", label: "BELGIUM" },
	{ value: "BF", label: "BURKINA FASO" },
	{ value: "BG", label: "BULGARIA" },
	{ value: "BH", label: "BAHRAIN" },
	{ value: "BI", label: "BURUNDI" },
	{ value: "BJ", label: "BENIN" },
	{ value: "BL", label: "ST. BARTHÉLEMY" },
	{ value: "BM", label: "BERMUDA" },
	{ value: "BN", label: "BRUNEI" },
	{ value: "BO", label: "BOLIVIA" },
	{ value: "BQ", label: "CARIBBEAN NETHERLANDS" },
	{ value: "BR", label: "BRAZIL" },
	{ value: "BS", label: "BAHAMAS" },
	{ value: "BT", label: "BHUTAN" },
	{ value: "BU", label: "MYANMAR (BURMA)" },
	{ value: "BV", label: "BOUVET ISLAND" },
	{ value: "BW", label: "BOTSWANA" },
	{ value: "BY", label: "BELARUS" },
	{ value: "BZ", label: "BELIZE" },
	{ value: "CA", label: "CANADA" },
	{ value: "CC", label: "COCOS (KEELING) ISLANDS" },
	{ value: "CD", label: "CONGO - KINSHASA" },
	{ value: "CF", label: "CENTRAL AFRICAN REPUBLIC" },
	{ value: "CG", label: "CONGO - BRAZZAVILLE" },
	{ value: "CH", label: "SWITZERLAND" },
	{ value: "CI", label: "CÔTE D’IVOIRE" },
	{ value: "CK", label: "COOK ISLANDS" },
	{ value: "CL", label: "CHILE" },
	{ value: "CM", label: "CAMEROON" },
	{ value: "CN", label: "CHINA" },
	{ value: "CO", label: "COLOMBIA" },
	{ value: "CP", label: "CLIPPERTON ISLAND" },
	{ value: "CQ", label: "SARK" },
	{ value: "CR", label: "COSTA RICA" },
	{ value: "CS", label: "SERBIA" },
	{ value: "CU", label: "CUBA" },
	{ value: "CV", label: "CAPE VERDE" },
	{ value: "CW", label: "CURAÇAO" },
	{ value: "CX", label: "CHRISTMAS ISLAND" },
	{ value: "CY", label: "CYPRUS" },
	{ value: "CZ", label: "CZECHIA" },
	{ value: "DD", label: "GERMANY" },
	{ value: "DE", label: "GERMANY" },
	{ value: "DG", label: "DIEGO GARCIA" },
	{ value: "DJ", label: "DJIBOUTI" },
	{ value: "DK", label: "DENMARK" },
	{ value: "DM", label: "DOMINICA" },
	{ value: "DO", label: "DOMINICAN REPUBLIC" },
	{ value: "DY", label: "BENIN" },
	{ value: "DZ", label: "ALGERIA" },
	{ value: "EA", label: "CEUTA & MELILLA" },
	{ value: "EC", label: "ECUADOR" },
	{ value: "EE", label: "ESTONIA" },
	{ value: "EG", label: "EGYPT" },
	{ value: "EH", label: "WESTERN SAHARA" },
	{ value: "ER", label: "ERITREA" },
	{ value: "ES", label: "SPAIN" },
	{ value: "ET", label: "ETHIOPIA" },
	{ value: "EZ", label: "EUROZONE" },
	{ value: "FI", label: "FINLAND" },
	{ value: "FJ", label: "FIJI" },
	{ value: "FK", label: "FALKLAND ISLANDS" },
	{ value: "FM", label: "MICRONESIA" },
	{ value: "FO", label: "FAROE ISLANDS" },
	{ value: "FR", label: "FRANCE" },
	{ value: "FX", label: "FRANCE" },
	{ value: "GA", label: "GABON" },
	{ value: "GB", label: "UNITED KINGDOM" },
	{ value: "GD", label: "GRENADA" },
	{ value: "GE", label: "GEORGIA" },
	{ value: "GF", label: "FRENCH GUIANA" },
	{ value: "GG", label: "GUERNSEY" },
	{ value: "GH", label: "GHANA" },
	{ value: "GI", label: "GIBRALTAR" },
	{ value: "GL", label: "GREENLAND" },
	{ value: "GM", label: "GAMBIA" },
	{ value: "GN", label: "GUINEA" },
	{ value: "GP", label: "GUADELOUPE" },
	{ value: "GQ", label: "EQUATORIAL GUINEA" },
	{ value: "GR", label: "GREECE" },
	{ value: "GS", label: "SOUTH GEORGIA & SOUTH SANDWICH ISLANDS" },
	{ value: "GT", label: "GUATEMALA" },
	{ value: "GU", label: "GUAM" },
	{ value: "GW", label: "GUINEA-BISSAU" },
	{ value: "GY", label: "GUYANA" },
	{ value: "HK", label: "HONG KONG SAR CHINA" },
	{ value: "HM", label: "HEARD & MCDONALD ISLANDS" },
	{ value: "HN", label: "HONDURAS" },
	{ value: "HR", label: "CROATIA" },
	{ value: "HT", label: "HAITI" },
	{ value: "HU", label: "HUNGARY" },
	{ value: "HV", label: "BURKINA FASO" },
	{ value: "IC", label: "CANARY ISLANDS" },
	{ value: "ID", label: "INDONESIA" },
	{ value: "IE", label: "IRELAND" },
	{ value: "IL", label: "ISRAEL" },
	{ value: "IM", label: "ISLE OF MAN" },
	{ value: "IN", label: "INDIA" },
	{ value: "IO", label: "BRITISH INDIAN OCEAN TERRITORY" },
	{ value: "IQ", label: "IRAQ" },
	{ value: "IR", label: "IRAN" },
	{ value: "IS", label: "ICELAND" },
	{ value: "IT", label: "ITALY" },
	{ value: "JE", label: "JERSEY" },
	{ value: "JM", label: "JAMAICA" },
	{ value: "JO", label: "JORDAN" },
	{ value: "JP", label: "JAPAN" },
	{ value: "KE", label: "KENYA" },
	{ value: "KG", label: "KYRGYZSTAN" },
	{ value: "KH", label: "CAMBODIA" },
	{ value: "KI", label: "KIRIBATI" },
	{ value: "KM", label: "COMOROS" },
	{ value: "KN", label: "ST. KITTS & NEVIS" },
	{ value: "KP", label: "NORTH KOREA" },
	{ value: "KR", label: "SOUTH KOREA" },
	{ value: "KW", label: "KUWAIT" },
	{ value: "KY", label: "CAYMAN ISLANDS" },
	{ value: "KZ", label: "KAZAKHSTAN" },
	{ value: "LA", label: "LAOS" },
	{ value: "LB", label: "LEBANON" },
	{ value: "LC", label: "ST. LUCIA" },
	{ value: "LI", label: "LIECHTENSTEIN" },
	{ value: "LK", label: "SRI LANKA" },
	{ value: "LR", label: "LIBERIA" },
	{ value: "LS", label: "LESOTHO" },
	{ value: "LT", label: "LITHUANIA" },
	{ value: "LU", label: "LUXEMBOURG" },
	{ value: "LV", label: "LATVIA" },
	{ value: "LY", label: "LIBYA" },
	{ value: "MA", label: "MOROCCO" },
	{ value: "MC", label: "MONACO" },
	{ value: "MD", label: "MOLDOVA" },
	{ value: "ME", label: "MONTENEGRO" },
	{ value: "MF", label: "ST. MARTIN" },
	{ value: "MG", label: "MADAGASCAR" },
	{ value: "MH", label: "MARSHALL ISLANDS" },
	{ value: "MK", label: "NORTH MACEDONIA" },
	{ value: "ML", label: "MALI" },
	{ value: "MM", label: "MYANMAR (BURMA)" },
	{ value: "MN", label: "MONGOLIA" },
	{ value: "MO", label: "MACAO SAR CHINA" },
	{ value: "MP", label: "NORTHERN MARIANA ISLANDS" },
	{ value: "MQ", label: "MARTINIQUE" },
	{ value: "MR", label: "MAURITANIA" },
	{ value: "MS", label: "MONTSERRAT" },
	{ value: "MT", label: "MALTA" },
	{ value: "MU", label: "MAURITIUS" },
	{ value: "MV", label: "MALDIVES" },
	{ value: "MW", label: "MALAWI" },
	{ value: "MX", label: "MEXICO" },
	{ value: "MY", label: "MALAYSIA" },
	{ value: "MZ", label: "MOZAMBIQUE" },
	{ value: "NA", label: "NAMIBIA" },
	{ value: "NC", label: "NEW CALEDONIA" },
	{ value: "NE", label: "NIGER" },
	{ value: "NF", label: "NORFOLK ISLAND" },
	{ value: "NG", label: "NIGERIA" },
	{ value: "NH", label: "VANUATU" },
	{ value: "NI", label: "NICARAGUA" },
	{ value: "NL", label: "NETHERLANDS" },
	{ value: "NO", label: "NORWAY" },
	{ value: "NP", label: "NEPAL" },
	{ value: "NR", label: "NAURU" },
	{ value: "NU", label: "NIUE" },
	{ value: "NZ", label: "NEW ZEALAND" },
	{ value: "OM", label: "OMAN" },
	{ value: "PA", label: "PANAMA" },
	{ value: "PE", label: "PERU" },
	{ value: "PF", label: "FRENCH POLYNESIA" },
	{ value: "PG", label: "PAPUA NEW GUINEA" },
	{ value: "PH", label: "PHILIPPINES" },
	{ value: "PK", label: "PAKISTAN" },
	{ value: "PL", label: "POLAND" },
	{ value: "PM", label: "ST. PIERRE & MIQUELON" },
	{ value: "PN", label: "PITCAIRN ISLANDS" },
	{ value: "PR", label: "PUERTO RICO" },
	{ value: "PS", label: "PALESTINIAN TERRITORIES" },
	{ value: "PT", label: "PORTUGAL" },
	{ value: "PW", label: "PALAU" },
	{ value: "PY", label: "PARAGUAY" },
	{ value: "QA", label: "QATAR" },
	{ value: "RE", label: "RÉUNION" },
	{ value: "RH", label: "ZIMBABWE" },
	{ value: "RO", label: "ROMANIA" },
	{ value: "RS", label: "SERBIA" },
	{ value: "RU", label: "RUSSIA" },
	{ value: "RW", label: "RWANDA" },
	{ value: "SA", label: "SAUDI ARABIA" },
	{ value: "SB", label: "SOLOMON ISLANDS" },
	{ value: "SC", label: "SEYCHELLES" },
	{ value: "SD", label: "SUDAN" },
	{ value: "SE", label: "SWEDEN" },
	{ value: "SG", label: "SINGAPORE" },
	{ value: "SH", label: "ST. HELENA" },
	{ value: "SI", label: "SLOVENIA" },
	{ value: "SJ", label: "SVALBARD & JAN MAYEN" },
	{ value: "SK", label: "SLOVAKIA" },
	{ value: "SL", label: "SIERRA LEONE" },
	{ value: "SM", label: "SAN MARINO" },
	{ value: "SN", label: "SENEGAL" },
	{ value: "SO", label: "SOMALIA" },
	{ value: "SR", label: "SURINAME" },
	{ value: "SS", label: "SOUTH SUDAN" },
	{ value: "ST", label: "SÃO TOMÉ & PRÍNCIPE" },
	{ value: "SU", label: "RUSSIA" },
	{ value: "SV", label: "EL SALVADOR" },
	{ value: "SX", label: "SINT MAARTEN" },
	{ value: "SY", label: "SYRIA" },
	{ value: "SZ", label: "ESWATINI" },
	{ value: "TA", label: "TRISTAN DA CUNHA" },
	{ value: "TC", label: "TURKS & CAICOS ISLANDS" },
	{ value: "TD", label: "CHAD" },
	{ value: "TF", label: "FRENCH SOUTHERN TERRITORIES" },
	{ value: "TG", label: "TOGO" },
	{ value: "TH", label: "THAILAND" },
	{ value: "TJ", label: "TAJIKISTAN" },
	{ value: "TK", label: "TOKELAU" },
	{ value: "TL", label: "TIMOR-LESTE" },
	{ value: "TM", label: "TURKMENISTAN" },
	{ value: "TN", label: "TUNISIA" },
	{ value: "TO", label: "TONGA" },
	{ value: "TP", label: "TIMOR-LESTE" },
	{ value: "TR", label: "TÜRKIYE" },
	{ value: "TT", label: "TRINIDAD & TOBAGO" },
	{ value: "TV", label: "TUVALU" },
	{ value: "TW", label: "TAIWAN" },
	{ value: "TZ", label: "TANZANIA" },
	{ value: "UA", label: "UKRAINE" },
	{ value: "UG", label: "UGANDA" },
	{ value: "UK", label: "UNITED KINGDOM" },
	{ value: "UM", label: "U.S. OUTLYING ISLANDS" },
	{ value: "US", label: "UNITED STATES" },
	{ value: "UY", label: "URUGUAY" },
	{ value: "UZ", label: "UZBEKISTAN" },
	{ value: "VA", label: "VATICAN CITY" },
	{ value: "VC", label: "ST. VINCENT & GRENADINES" },
	{ value: "VD", label: "VIETNAM" },
	{ value: "VE", label: "VENEZUELA" },
	{ value: "VG", label: "BRITISH VIRGIN ISLANDS" },
	{ value: "VI", label: "U.S. VIRGIN ISLANDS" },
	{ value: "VN", label: "VIETNAM" },
	{ value: "VU", label: "VANUATU" },
	{ value: "WF", label: "WALLIS & FUTUNA" },
	{ value: "WS", label: "SAMOA" },
	{ value: "XK", label: "KOSOVO" },
	{ value: "YD", label: "YEMEN" },
	{ value: "YE", label: "YEMEN" },
	{ value: "YT", label: "MAYOTTE" },
	{ value: "YU", label: "SERBIA" },
	{ value: "ZA", label: "SOUTH AFRICA" },
	{ value: "ZM", label: "ZAMBIA" },
	{ value: "ZR", label: "CONGO - KINSHASA" },
	{ value: "ZW", label: "ZIMBABWE" }
]);

export const STATE_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'https://www.icegate.gov.in/Webappl/state_det_all.jsp',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 40
});

/** Two-digit GST/ICEGATE state codes. Leading zeroes are significant. */
export const STATE_OPTIONS = freeze([
	{ value: "01", label: "JAMMU AND KASHMIR" },
	{ value: "02", label: "HIMACHAL PRADESH" },
	{ value: "03", label: "PUNJAB" },
	{ value: "04", label: "CHANDIGARH" },
	{ value: "05", label: "UTTARAKHAND" },
	{ value: "06", label: "HARYANA" },
	{ value: "07", label: "DELHI" },
	{ value: "08", label: "RAJASTHAN" },
	{ value: "09", label: "UTTAR PRADESH" },
	{ value: "10", label: "BIHAR" },
	{ value: "11", label: "SIKKIM" },
	{ value: "12", label: "ARUNACHAL PRADESH" },
	{ value: "13", label: "NAGALAND" },
	{ value: "14", label: "MANIPUR" },
	{ value: "15", label: "MIZORAM" },
	{ value: "16", label: "TRIPURA" },
	{ value: "17", label: "MEGHALAYA" },
	{ value: "18", label: "ASSAM" },
	{ value: "19", label: "WEST BENGAL" },
	{ value: "20", label: "JHARKHAND" },
	{ value: "21", label: "ODISHA" },
	{ value: "22", label: "CHHATTISGARH" },
	{ value: "23", label: "MADHYA PRADESH" },
	{ value: "24", label: "GUJARAT" },
	{ value: "25", label: "DAMAN AND DIU" },
	{ value: "26", label: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU" },
	{ value: "27", label: "MAHARASHTRA" },
	{ value: "28", label: "ANDHRA PRADESH" },
	{ value: "29", label: "KARNATAKA" },
	{ value: "30", label: "GOA" },
	{ value: "31", label: "LAKSHADWEEP" },
	{ value: "32", label: "KERALA" },
	{ value: "33", label: "TAMIL NADU" },
	{ value: "34", label: "PUDUCHERRY" },
	{ value: "35", label: "ANDAMAN AND NICOBAR ISLANDS" },
	{ value: "36", label: "TELANGANA" },
	{ value: "37", label: "ANDHRA PRADESH (NEW)" },
	{ value: "38", label: "LADAKH" },
	{ value: "97", label: "OTHER TERRITORY" },
	{ value: "99", label: "CENTRE JURISDICTION" }
]);

export const FTA_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'https://www.icegate.gov.in/Webappl/Ftp',
	retrievedAt: '2026-08-29',
	sha256: '',
	entryCount: 21
});

export const FTA_OPTIONS = freeze([
	{ value: "FTA0SL" },
	{ value: "FTA0SA" },
	{ value: "FTA0NL" },
	{ value: "FTA0BT" },
	{ value: "FTA0TH" },
	{ value: "CEPASG" },
	{ value: "CEPASEA" },
	{ value: "CEPAKR" },
	{ value: "CEPAJP" },
	{ value: "CECAMY" },
	{ value: "PTAAPTA" },
	{ value: "GSTP" },
	{ value: "PTA0SA" },
	{ value: "PTA0AF" },
	{ value: "PTA0MER" },
	{ value: "PTA0CL" },
	{ value: "NCPTI" },
	{ value: "ECTAAU" },
	{ value: "CEPAOM" },
	{ value: "CEPAAE" },
	{ value: "CETAUK" }
]);

export const DISTRICT_PROVENANCE: CatalogProvenance = Object.freeze({
	sourceUrl: 'icegate-state-district-list',
	retrievedAt: '2026-08-29',
	sha256: '660cd42aea65600182798edc107708b86642313b6e91411e86b5340df5d30f76',
	entryCount: 725
});

/**
 * ICEGATE district codes, each scoped to its state by `parentValue`. District codes
 * are unique across the whole list, but the dropdown still filters on the state so a
 * district can never be picked under the wrong one.
 */
export const DISTRICT_OPTIONS = freeze([
	{ value: "01", label: "ANANTNAG", parentValue: "01" },
	{ value: "02", label: "Budgam", parentValue: "01" },
	{ value: "03", label: "BARAMULLA", parentValue: "01" },
	{ value: "04", label: "DODA", parentValue: "01" },
	{ value: "05", label: "JAMMU", parentValue: "01" },
	{ value: "07", label: "KATHUA", parentValue: "01" },
	{ value: "08", label: "KUPWARA", parentValue: "01" },
	{ value: "10", label: "POONCH", parentValue: "01" },
	{ value: "11", label: "PULWAMA", parentValue: "01" },
	{ value: "12", label: "RAJOURI", parentValue: "01" },
	{ value: "13", label: "SRINAGAR", parentValue: "01" },
	{ value: "14", label: "UDHAMPUR", parentValue: "01" },
	{ value: "620", label: "KISHTWAR", parentValue: "01" },
	{ value: "621", label: "RAMBAN", parentValue: "01" },
	{ value: "622", label: "KULGAM", parentValue: "01" },
	{ value: "623", label: "BANDIPORA", parentValue: "01" },
	{ value: "624", label: "SAMBA", parentValue: "01" },
	{ value: "625", label: "SHOPIAN", parentValue: "01" },
	{ value: "626", label: "GANDERBAL", parentValue: "01" },
	{ value: "627", label: "REASI", parentValue: "01" },
	{ value: "15", label: "BILASPUR", parentValue: "02" },
	{ value: "16", label: "CHAMBA", parentValue: "02" },
	{ value: "17", label: "HAMIRPUR", parentValue: "02" },
	{ value: "18", label: "KANGRA", parentValue: "02" },
	{ value: "19", label: "KINNAUR", parentValue: "02" },
	{ value: "20", label: "KULLU", parentValue: "02" },
	{ value: "21", label: "LAHUL AND SPITI", parentValue: "02" },
	{ value: "22", label: "MANDI", parentValue: "02" },
	{ value: "23", label: "SHIMLA", parentValue: "02" },
	{ value: "24", label: "SIRMAUR", parentValue: "02" },
	{ value: "25", label: "SOLAN", parentValue: "02" },
	{ value: "26", label: "UNA", parentValue: "02" },
	{ value: "27", label: "AMRITSAR", parentValue: "03" },
	{ value: "28", label: "BATHINDA", parentValue: "03" },
	{ value: "29", label: "FARIDKOT", parentValue: "03" },
	{ value: "30", label: "FATEHGARH SAHIB", parentValue: "03" },
	{ value: "31", label: "FIROZEPUR", parentValue: "03" },
	{ value: "32", label: "GURDASPUR", parentValue: "03" },
	{ value: "33", label: "HOSHIARPUR", parentValue: "03" },
	{ value: "34", label: "JALANDHAR", parentValue: "03" },
	{ value: "35", label: "KAPURTHALA", parentValue: "03" },
	{ value: "36", label: "LUDHIANA", parentValue: "03" },
	{ value: "37", label: "MANSA", parentValue: "03" },
	{ value: "38", label: "MOGA", parentValue: "03" },
	{ value: "39", label: "SRI MUKTSAR SAHIB", parentValue: "03" },
	{ value: "40", label: "Shahid Bhagat Singh Nagar", parentValue: "03" },
	{ value: "41", label: "PATIALA", parentValue: "03" },
	{ value: "42", label: "RUPNAGAR", parentValue: "03" },
	{ value: "43", label: "SANGRUR", parentValue: "03" },
	{ value: "605", label: "BARNALA", parentValue: "03" },
	{ value: "608", label: "S.A.S Nagar", parentValue: "03" },
	{ value: "609", label: "Tarn Taran", parentValue: "03" },
	{ value: "651", label: "FAZILKA", parentValue: "03" },
	{ value: "662", label: "PATHANKOT", parentValue: "03" },
	{ value: "44", label: "CHANDIGARH", parentValue: "04" },
	{ value: "45", label: "ALMORA", parentValue: "05" },
	{ value: "46", label: "BAGESHWAR", parentValue: "05" },
	{ value: "47", label: "CHAMOLI", parentValue: "05" },
	{ value: "48", label: "CHAMPAWAT", parentValue: "05" },
	{ value: "49", label: "DEHRADUN", parentValue: "05" },
	{ value: "50", label: "HARIDWAR", parentValue: "05" },
	{ value: "51", label: "NAINITAL", parentValue: "05" },
	{ value: "52", label: "PAURI GARHWAL", parentValue: "05" },
	{ value: "53", label: "PITHORAGARH", parentValue: "05" },
	{ value: "54", label: "RUDRA PRAYAG", parentValue: "05" },
	{ value: "55", label: "TEHRI GARHWAL", parentValue: "05" },
	{ value: "56", label: "UDAM SINGH NAGAR", parentValue: "05" },
	{ value: "57", label: "UTTAR KASHI", parentValue: "05" },
	{ value: "58", label: "AMBALA", parentValue: "06" },
	{ value: "59", label: "BHIWANI", parentValue: "06" },
	{ value: "60", label: "FARIDABAD", parentValue: "06" },
	{ value: "61", label: "FATEHABAD", parentValue: "06" },
	{ value: "62", label: "GURUGRAM", parentValue: "06" },
	{ value: "63", label: "HISAR", parentValue: "06" },
	{ value: "64", label: "JHAJJAR", parentValue: "06" },
	{ value: "65", label: "JIND", parentValue: "06" },
	{ value: "66", label: "KAITHAL", parentValue: "06" },
	{ value: "67", label: "KARNAL", parentValue: "06" },
	{ value: "68", label: "KURUKSHETRA", parentValue: "06" },
	{ value: "69", label: "MAHENDRAGARH", parentValue: "06" },
	{ value: "70", label: "PANCHKULA", parentValue: "06" },
	{ value: "71", label: "PANIPAT", parentValue: "06" },
	{ value: "72", label: "REWARI", parentValue: "06" },
	{ value: "73", label: "ROHTAK", parentValue: "06" },
	{ value: "74", label: "SIRSA", parentValue: "06" },
	{ value: "75", label: "SONIPAT", parentValue: "06" },
	{ value: "76", label: "YAMUNANAGAR", parentValue: "06" },
	{ value: "604", label: "NUH", parentValue: "06" },
	{ value: "619", label: "PALWAL", parentValue: "06" },
	{ value: "701", label: "CHARKI DADRI", parentValue: "06" },
	{ value: "77", label: "CENTRAL", parentValue: "07" },
	{ value: "78", label: "EAST", parentValue: "07" },
	{ value: "79", label: "NEW DELHI", parentValue: "07" },
	{ value: "80", label: "NORTH", parentValue: "07" },
	{ value: "81", label: "NORTH EAST", parentValue: "07" },
	{ value: "82", label: "NORTH WEST", parentValue: "07" },
	{ value: "83", label: "SOUTH", parentValue: "07" },
	{ value: "84", label: "SOUTH WEST", parentValue: "07" },
	{ value: "85", label: "WEST", parentValue: "07" },
	{ value: "670", label: "South East", parentValue: "07" },
	{ value: "671", label: "SHAHDARA", parentValue: "07" },
	{ value: "86", label: "AJMER", parentValue: "08" },
	{ value: "87", label: "ALWAR", parentValue: "08" },
	{ value: "88", label: "BANSWARA", parentValue: "08" },
	{ value: "89", label: "BARAN", parentValue: "08" },
	{ value: "90", label: "BARMER", parentValue: "08" },
	{ value: "91", label: "BHARATPUR", parentValue: "08" },
	{ value: "92", label: "BHILWARA", parentValue: "08" },
	{ value: "93", label: "BIKANER", parentValue: "08" },
	{ value: "94", label: "BUNDI", parentValue: "08" },
	{ value: "95", label: "CHITTORGARH", parentValue: "08" },
	{ value: "96", label: "CHURU", parentValue: "08" },
	{ value: "97", label: "DAUSA", parentValue: "08" },
	{ value: "98", label: "DHOLPUR", parentValue: "08" },
	{ value: "99", label: "DUNGARPUR", parentValue: "08" },
	{ value: "100", label: "GANGANAGAR", parentValue: "08" },
	{ value: "101", label: "HANUMANGARH", parentValue: "08" },
	{ value: "102", label: "JAIPUR", parentValue: "08" },
	{ value: "103", label: "JAISALMER", parentValue: "08" },
	{ value: "104", label: "JALORE", parentValue: "08" },
	{ value: "105", label: "JHALAWAR", parentValue: "08" },
	{ value: "106", label: "JHUNJHUNU", parentValue: "08" },
	{ value: "107", label: "JODHPUR", parentValue: "08" },
	{ value: "108", label: "KARAULI", parentValue: "08" },
	{ value: "109", label: "KOTA", parentValue: "08" },
	{ value: "110", label: "NAGAUR", parentValue: "08" },
	{ value: "111", label: "PALI", parentValue: "08" },
	{ value: "112", label: "RAJSAMAND", parentValue: "08" },
	{ value: "113", label: "SAWAI MADHOPUR", parentValue: "08" },
	{ value: "114", label: "SIKAR", parentValue: "08" },
	{ value: "115", label: "SIROHI", parentValue: "08" },
	{ value: "116", label: "TONK", parentValue: "08" },
	{ value: "117", label: "UDAIPUR", parentValue: "08" },
	{ value: "629", label: "PRATAPGARH", parentValue: "08" },
	{ value: "118", label: "AGRA", parentValue: "09" },
	{ value: "119", label: "ALIGARH", parentValue: "09" },
	{ value: "120", label: "PRAYAGRAJ", parentValue: "09" },
	{ value: "121", label: "AMBEDKAR NAGAR", parentValue: "09" },
	{ value: "122", label: "AURAIYA", parentValue: "09" },
	{ value: "123", label: "AZAMGARH", parentValue: "09" },
	{ value: "124", label: "BAGHPAT", parentValue: "09" },
	{ value: "125", label: "BAHRAICH", parentValue: "09" },
	{ value: "126", label: "BALLIA", parentValue: "09" },
	{ value: "127", label: "BALRAMPUR", parentValue: "09" },
	{ value: "128", label: "BANDA", parentValue: "09" },
	{ value: "129", label: "BARABANKI", parentValue: "09" },
	{ value: "130", label: "BAREILLY", parentValue: "09" },
	{ value: "131", label: "BASTI", parentValue: "09" },
	{ value: "132", label: "BIJNOR", parentValue: "09" },
	{ value: "133", label: "BUDAUN", parentValue: "09" },
	{ value: "134", label: "BULANDSHAHR", parentValue: "09" },
	{ value: "135", label: "CHANDAULI", parentValue: "09" },
	{ value: "136", label: "CHITRAKOOT", parentValue: "09" },
	{ value: "137", label: "DEORIA", parentValue: "09" },
	{ value: "138", label: "ETAH", parentValue: "09" },
	{ value: "139", label: "ETAWAH", parentValue: "09" },
	{ value: "140", label: "AYODHYA", parentValue: "09" },
	{ value: "141", label: "FARRUKHABAD", parentValue: "09" },
	{ value: "142", label: "FATEHPUR", parentValue: "09" },
	{ value: "143", label: "FIROZABAD", parentValue: "09" },
	{ value: "144", label: "GAUTAM BUDDHA NAGAR", parentValue: "09" },
	{ value: "145", label: "GHAZIABAD", parentValue: "09" },
	{ value: "146", label: "GHAZIPUR", parentValue: "09" },
	{ value: "147", label: "GONDA", parentValue: "09" },
	{ value: "148", label: "GORAKHPUR", parentValue: "09" },
	{ value: "149", label: "HAMIRPUR", parentValue: "09" },
	{ value: "150", label: "HARDOI", parentValue: "09" },
	{ value: "151", label: "JALAUN", parentValue: "09" },
	{ value: "152", label: "JAUNPUR", parentValue: "09" },
	{ value: "153", label: "JHANSI", parentValue: "09" },
	{ value: "154", label: "AMROHA", parentValue: "09" },
	{ value: "155", label: "KANNAUJ", parentValue: "09" },
	{ value: "156", label: "KANPUR DEHAT", parentValue: "09" },
	{ value: "157", label: "KANPUR NAGAR", parentValue: "09" },
	{ value: "158", label: "KAUSHAMBI", parentValue: "09" },
	{ value: "159", label: "KHERI", parentValue: "09" },
	{ value: "160", label: "KUSHI NAGAR", parentValue: "09" },
	{ value: "161", label: "LALITPUR", parentValue: "09" },
	{ value: "162", label: "LUCKNOW", parentValue: "09" },
	{ value: "163", label: "HATHRAS", parentValue: "09" },
	{ value: "164", label: "MAHARAJGANJ", parentValue: "09" },
	{ value: "165", label: "MAHOBA", parentValue: "09" },
	{ value: "166", label: "MAINPURI", parentValue: "09" },
	{ value: "167", label: "MATHURA", parentValue: "09" },
	{ value: "168", label: "MAU", parentValue: "09" },
	{ value: "169", label: "MEERUT", parentValue: "09" },
	{ value: "170", label: "MIRZAPUR", parentValue: "09" },
	{ value: "171", label: "MORADABAD", parentValue: "09" },
	{ value: "172", label: "MUZAFFARNAGAR", parentValue: "09" },
	{ value: "173", label: "PILIBHIT", parentValue: "09" },
	{ value: "174", label: "PRATAPGARH", parentValue: "09" },
	{ value: "175", label: "RAE BARELI", parentValue: "09" },
	{ value: "176", label: "RAMPUR", parentValue: "09" },
	{ value: "177", label: "SAHARANPUR", parentValue: "09" },
	{ value: "178", label: "SANT KABEER NAGAR", parentValue: "09" },
	{ value: "179", label: "BHADOHI", parentValue: "09" },
	{ value: "180", label: "SHAHJAHANPUR", parentValue: "09" },
	{ value: "181", label: "SHRAVASTI", parentValue: "09" },
	{ value: "182", label: "SIDDHARTH NAGAR", parentValue: "09" },
	{ value: "183", label: "SITAPUR", parentValue: "09" },
	{ value: "184", label: "SONBHADRA", parentValue: "09" },
	{ value: "185", label: "SULTANPUR", parentValue: "09" },
	{ value: "186", label: "UNNAO", parentValue: "09" },
	{ value: "187", label: "VARANASI", parentValue: "09" },
	{ value: "633", label: "Kasganj", parentValue: "09" },
	{ value: "640", label: "Amethi", parentValue: "09" },
	{ value: "659", label: "SAMBHAL", parentValue: "09" },
	{ value: "660", label: "SHAMLI", parentValue: "09" },
	{ value: "661", label: "HAPUR", parentValue: "09" },
	{ value: "188", label: "ARARIA", parentValue: "10" },
	{ value: "189", label: "AURANGABAD", parentValue: "10" },
	{ value: "190", label: "BANKA", parentValue: "10" },
	{ value: "191", label: "BEGUSARAI", parentValue: "10" },
	{ value: "192", label: "BHAGALPUR", parentValue: "10" },
	{ value: "193", label: "BHOJPUR", parentValue: "10" },
	{ value: "194", label: "BUXAR", parentValue: "10" },
	{ value: "195", label: "DARBHANGA", parentValue: "10" },
	{ value: "196", label: "GAYA", parentValue: "10" },
	{ value: "197", label: "GOPALGANJ", parentValue: "10" },
	{ value: "198", label: "JAMUI", parentValue: "10" },
	{ value: "199", label: "JEHANABAD", parentValue: "10" },
	{ value: "200", label: "KAIMUR (BHABUA)", parentValue: "10" },
	{ value: "201", label: "KATIHAR", parentValue: "10" },
	{ value: "202", label: "KHAGARIA", parentValue: "10" },
	{ value: "203", label: "KISHANGANJ", parentValue: "10" },
	{ value: "204", label: "LAKHISARAI", parentValue: "10" },
	{ value: "205", label: "MADHEPURA", parentValue: "10" },
	{ value: "206", label: "MADHUBANI", parentValue: "10" },
	{ value: "207", label: "MUNGER", parentValue: "10" },
	{ value: "208", label: "MUZAFFARPUR", parentValue: "10" },
	{ value: "209", label: "NALANDA", parentValue: "10" },
	{ value: "210", label: "NAWADA", parentValue: "10" },
	{ value: "211", label: "PASHCHIM CHAMPARAN", parentValue: "10" },
	{ value: "212", label: "PATNA", parentValue: "10" },
	{ value: "213", label: "PURBI CHAMPARAN", parentValue: "10" },
	{ value: "214", label: "PURNIA", parentValue: "10" },
	{ value: "215", label: "ROHTAS", parentValue: "10" },
	{ value: "216", label: "SAHARSA", parentValue: "10" },
	{ value: "217", label: "SAMASTIPUR", parentValue: "10" },
	{ value: "218", label: "SARAN", parentValue: "10" },
	{ value: "219", label: "SHEIKHPURA", parentValue: "10" },
	{ value: "220", label: "SHEOHAR", parentValue: "10" },
	{ value: "221", label: "SITAMARHI", parentValue: "10" },
	{ value: "222", label: "SIWAN", parentValue: "10" },
	{ value: "223", label: "SUPAUL", parentValue: "10" },
	{ value: "224", label: "VAISHALI", parentValue: "10" },
	{ value: "611", label: "ARWAL", parentValue: "10" },
	{ value: "225", label: "EAST DISTRICT", parentValue: "11" },
	{ value: "226", label: "NORTH DISTRICT", parentValue: "11" },
	{ value: "227", label: "SOUTH DISTRICT", parentValue: "11" },
	{ value: "228", label: "WEST DISTRICT", parentValue: "11" },
	{ value: "229", label: "CHANGLANG", parentValue: "12" },
	{ value: "230", label: "DIBANG VALLEY", parentValue: "12" },
	{ value: "231", label: "EAST KAMENG", parentValue: "12" },
	{ value: "232", label: "EAST SIANG", parentValue: "12" },
	{ value: "233", label: "KURUNG KUMEY", parentValue: "12" },
	{ value: "234", label: "LOHIT", parentValue: "12" },
	{ value: "235", label: "LOWER DIBANG VALLEY", parentValue: "12" },
	{ value: "236", label: "LOWER SUBANSIRI", parentValue: "12" },
	{ value: "237", label: "PAPUM PARE", parentValue: "12" },
	{ value: "238", label: "TAWANG", parentValue: "12" },
	{ value: "239", label: "TIRAP", parentValue: "12" },
	{ value: "240", label: "UPPER SIANG", parentValue: "12" },
	{ value: "241", label: "UPPER SUBANSIRI", parentValue: "12" },
	{ value: "242", label: "WEST KAMENG", parentValue: "12" },
	{ value: "243", label: "WEST SIANG", parentValue: "12" },
	{ value: "628", label: "ANJAW", parentValue: "12" },
	{ value: "666", label: "LONGDING", parentValue: "12" },
	{ value: "677", label: "KRA  DAADI", parentValue: "12" },
	{ value: "678", label: "NAMSAI", parentValue: "12" },
	{ value: "679", label: "SIANG", parentValue: "12" },
	{ value: "718", label: "KAMLE", parentValue: "12" },
	{ value: "719", label: "LOWER SIANG", parentValue: "12" },
	{ value: "723", label: "PAKKE KESSANG", parentValue: "12" },
	{ value: "724", label: "LEPARADA", parentValue: "12" },
	{ value: "725", label: "SHI YOMI", parentValue: "12" },
	{ value: "244", label: "DIMAPUR", parentValue: "13" },
	{ value: "245", label: "KOHIMA", parentValue: "13" },
	{ value: "246", label: "MOKOKCHUNG", parentValue: "13" },
	{ value: "247", label: "MON", parentValue: "13" },
	{ value: "248", label: "PHEK", parentValue: "13" },
	{ value: "249", label: "TUENSANG", parentValue: "13" },
	{ value: "250", label: "WOKHA", parentValue: "13" },
	{ value: "251", label: "ZUNHEBOTO", parentValue: "13" },
	{ value: "613", label: "PEREN", parentValue: "13" },
	{ value: "614", label: "KIPHIRE", parentValue: "13" },
	{ value: "615", label: "LONGLENG", parentValue: "13" },
	{ value: "252", label: "BISHNUPUR", parentValue: "14" },
	{ value: "253", label: "CHANDEL", parentValue: "14" },
	{ value: "254", label: "CHURACHANDPUR", parentValue: "14" },
	{ value: "255", label: "IMPHAL EAST", parentValue: "14" },
	{ value: "256", label: "IMPHAL WEST", parentValue: "14" },
	{ value: "257", label: "SENAPATI", parentValue: "14" },
	{ value: "258", label: "TAMENGLONG", parentValue: "14" },
	{ value: "259", label: "THOUBAL", parentValue: "14" },
	{ value: "260", label: "UKHRUL", parentValue: "14" },
	{ value: "711", label: "KAKCHING", parentValue: "14" },
	{ value: "712", label: "KANGPOKPI", parentValue: "14" },
	{ value: "713", label: "JIRIBAM", parentValue: "14" },
	{ value: "714", label: "NONEY", parentValue: "14" },
	{ value: "715", label: "PHERZAWL", parentValue: "14" },
	{ value: "716", label: "TENGNOUPAL", parentValue: "14" },
	{ value: "717", label: "KAMJONG", parentValue: "14" },
	{ value: "261", label: "AIZAWL", parentValue: "15" },
	{ value: "262", label: "CHAMPHAI", parentValue: "15" },
	{ value: "263", label: "KOLASIB", parentValue: "15" },
	{ value: "264", label: "LAWNGTLAI", parentValue: "15" },
	{ value: "265", label: "LUNGLEI", parentValue: "15" },
	{ value: "266", label: "MAMIT", parentValue: "15" },
	{ value: "267", label: "SAIHA", parentValue: "15" },
	{ value: "268", label: "SERCHHIP", parentValue: "15" },
	{ value: "269", label: "Dhalai", parentValue: "16" },
	{ value: "270", label: "North Tripura", parentValue: "16" },
	{ value: "271", label: "South Tripura", parentValue: "16" },
	{ value: "272", label: "West Tripura", parentValue: "16" },
	{ value: "652", label: "Khowai", parentValue: "16" },
	{ value: "653", label: "Sepahijala", parentValue: "16" },
	{ value: "654", label: "Gomati", parentValue: "16" },
	{ value: "655", label: "Unakoti", parentValue: "16" },
	{ value: "273", label: "EAST GARO HILLS", parentValue: "17" },
	{ value: "274", label: "EAST KHASI HILLS", parentValue: "17" },
	{ value: "275", label: "WEST JAINTIA HILLS", parentValue: "17" },
	{ value: "276", label: "RI BHOI", parentValue: "17" },
	{ value: "277", label: "SOUTH GARO HILLS", parentValue: "17" },
	{ value: "278", label: "WEST GARO HILLS", parentValue: "17" },
	{ value: "279", label: "WEST KHASI HILLS", parentValue: "17" },
	{ value: "656", label: "NORTH GARO HILLS", parentValue: "17" },
	{ value: "657", label: "EAST JAINTIA HILLS", parentValue: "17" },
	{ value: "658", label: "SOUTH WEST KHASI HILLS", parentValue: "17" },
	{ value: "663", label: "SOUTH WEST GARO HILLS", parentValue: "17" },
	{ value: "280", label: "BARPETA", parentValue: "18" },
	{ value: "281", label: "BONGAIGAON", parentValue: "18" },
	{ value: "282", label: "CACHAR", parentValue: "18" },
	{ value: "283", label: "DARRANG", parentValue: "18" },
	{ value: "284", label: "DHEMAJI", parentValue: "18" },
	{ value: "285", label: "DHUBRI", parentValue: "18" },
	{ value: "286", label: "DIBRUGARH", parentValue: "18" },
	{ value: "287", label: "GOALPARA", parentValue: "18" },
	{ value: "288", label: "GOLAGHAT", parentValue: "18" },
	{ value: "289", label: "HAILAKANDI", parentValue: "18" },
	{ value: "290", label: "JORHAT", parentValue: "18" },
	{ value: "291", label: "KAMRUP", parentValue: "18" },
	{ value: "292", label: "KARBI ANGLONG", parentValue: "18" },
	{ value: "293", label: "KARIMGANJ", parentValue: "18" },
	{ value: "294", label: "KOKRAJHAR", parentValue: "18" },
	{ value: "295", label: "LAKHIMPUR", parentValue: "18" },
	{ value: "296", label: "MARIGAON", parentValue: "18" },
	{ value: "297", label: "NAGAON", parentValue: "18" },
	{ value: "298", label: "NALBARI", parentValue: "18" },
	{ value: "299", label: "DIMA HASAO", parentValue: "18" },
	{ value: "300", label: "SIVASAGAR", parentValue: "18" },
	{ value: "301", label: "SONITPUR", parentValue: "18" },
	{ value: "302", label: "TINSUKIA", parentValue: "18" },
	{ value: "612", label: "CHIRANG", parentValue: "18" },
	{ value: "616", label: "BAKSA", parentValue: "18" },
	{ value: "617", label: "UDALGURI", parentValue: "18" },
	{ value: "618", label: "KAMRUP METRO", parentValue: "18" },
	{ value: "705", label: "Biswanath", parentValue: "18" },
	{ value: "706", label: "MAJULI", parentValue: "18" },
	{ value: "707", label: "SOUTH SALMARA MANCACHAR", parentValue: "18" },
	{ value: "708", label: "CHARAIDEO", parentValue: "18" },
	{ value: "709", label: "HOJAI", parentValue: "18" },
	{ value: "710", label: "WEST KARBI ANGLONG", parentValue: "18" },
	{ value: "303", label: "24 PARAGANAS NORTH", parentValue: "19" },
	{ value: "304", label: "24 PARAGANAS SOUTH", parentValue: "19" },
	{ value: "305", label: "BANKURA", parentValue: "19" },
	{ value: "306", label: "PURBA BARDHAMAN", parentValue: "19" },
	{ value: "307", label: "BIRBHUM", parentValue: "19" },
	{ value: "308", label: "COOCHBEHAR", parentValue: "19" },
	{ value: "309", label: "DARJEELING", parentValue: "19" },
	{ value: "310", label: "DINAJPUR DAKSHIN", parentValue: "19" },
	{ value: "311", label: "DINAJPUR UTTAR", parentValue: "19" },
	{ value: "312", label: "HOOGHLY", parentValue: "19" },
	{ value: "313", label: "HOWRAH", parentValue: "19" },
	{ value: "314", label: "JALPAIGURI", parentValue: "19" },
	{ value: "315", label: "KOLKATA", parentValue: "19" },
	{ value: "316", label: "MALDAH", parentValue: "19" },
	{ value: "317", label: "MEDINIPUR EAST", parentValue: "19" },
	{ value: "318", label: "MEDINIPUR WEST", parentValue: "19" },
	{ value: "319", label: "MURSHIDABAD", parentValue: "19" },
	{ value: "320", label: "NADIA", parentValue: "19" },
	{ value: "321", label: "PURULIA", parentValue: "19" },
	{ value: "664", label: "Alipurduar", parentValue: "19" },
	{ value: "702", label: "KALIMPONG", parentValue: "19" },
	{ value: "703", label: "Jhargram", parentValue: "19" },
	{ value: "704", label: "PASCHIM BARDHAMAN", parentValue: "19" },
	{ value: "322", label: "BOKARO", parentValue: "20" },
	{ value: "323", label: "CHATRA", parentValue: "20" },
	{ value: "324", label: "DEOGHAR", parentValue: "20" },
	{ value: "325", label: "DHANBAD", parentValue: "20" },
	{ value: "326", label: "DUMKA", parentValue: "20" },
	{ value: "327", label: "EAST SINGHBUM", parentValue: "20" },
	{ value: "328", label: "GARHWA", parentValue: "20" },
	{ value: "329", label: "GIRIDIH", parentValue: "20" },
	{ value: "330", label: "GODDA", parentValue: "20" },
	{ value: "331", label: "GUMLA", parentValue: "20" },
	{ value: "332", label: "HAZARIBAGH", parentValue: "20" },
	{ value: "333", label: "JAMTARA", parentValue: "20" },
	{ value: "334", label: "KODERMA", parentValue: "20" },
	{ value: "335", label: "LATEHAR", parentValue: "20" },
	{ value: "336", label: "LOHARDAGA", parentValue: "20" },
	{ value: "337", label: "PAKUR", parentValue: "20" },
	{ value: "338", label: "PALAMU", parentValue: "20" },
	{ value: "339", label: "RANCHI", parentValue: "20" },
	{ value: "340", label: "SAHEBGANJ", parentValue: "20" },
	{ value: "341", label: "SARAIKELA KHARSAWAN", parentValue: "20" },
	{ value: "342", label: "SIMDEGA", parentValue: "20" },
	{ value: "343", label: "WEST SINGHBHUM", parentValue: "20" },
	{ value: "606", label: "KHUNTI", parentValue: "20" },
	{ value: "607", label: "RAMGARH", parentValue: "20" },
	{ value: "344", label: "ANUGUL", parentValue: "21" },
	{ value: "345", label: "BALANGIR", parentValue: "21" },
	{ value: "346", label: "BALESHWAR", parentValue: "21" },
	{ value: "347", label: "BARGARH", parentValue: "21" },
	{ value: "348", label: "BHADRAK", parentValue: "21" },
	{ value: "349", label: "BOUDH", parentValue: "21" },
	{ value: "350", label: "CUTTACK", parentValue: "21" },
	{ value: "351", label: "DEOGARH", parentValue: "21" },
	{ value: "352", label: "DHENKANAL", parentValue: "21" },
	{ value: "353", label: "GAJAPATI", parentValue: "21" },
	{ value: "354", label: "GANJAM", parentValue: "21" },
	{ value: "355", label: "JAGATSINGHAPUR", parentValue: "21" },
	{ value: "356", label: "JAJAPUR", parentValue: "21" },
	{ value: "357", label: "JHARSUGUDA", parentValue: "21" },
	{ value: "358", label: "KALAHANDI", parentValue: "21" },
	{ value: "359", label: "KANDHAMAL", parentValue: "21" },
	{ value: "360", label: "KENDRAPARA", parentValue: "21" },
	{ value: "361", label: "KENDUJHAR", parentValue: "21" },
	{ value: "362", label: "KHORDHA", parentValue: "21" },
	{ value: "363", label: "KORAPUT", parentValue: "21" },
	{ value: "364", label: "MALKANGIRI", parentValue: "21" },
	{ value: "365", label: "MAYURBHANJ", parentValue: "21" },
	{ value: "366", label: "NABARANGPUR", parentValue: "21" },
	{ value: "367", label: "NAYAGARH", parentValue: "21" },
	{ value: "368", label: "NUAPADA", parentValue: "21" },
	{ value: "369", label: "PURI", parentValue: "21" },
	{ value: "370", label: "RAYAGADA", parentValue: "21" },
	{ value: "371", label: "SAMBALPUR", parentValue: "21" },
	{ value: "372", label: "SONEPUR", parentValue: "21" },
	{ value: "373", label: "SUNDARGARH", parentValue: "21" },
	{ value: "374", label: "BASTAR", parentValue: "22" },
	{ value: "375", label: "BILASPUR", parentValue: "22" },
	{ value: "376", label: "DANTEWADA", parentValue: "22" },
	{ value: "377", label: "DHAMTARI", parentValue: "22" },
	{ value: "378", label: "DURG", parentValue: "22" },
	{ value: "379", label: "JANJGIR-CHAMPA", parentValue: "22" },
	{ value: "380", label: "JASHPUR", parentValue: "22" },
	{ value: "381", label: "KANKER", parentValue: "22" },
	{ value: "382", label: "KABIRDHAM", parentValue: "22" },
	{ value: "383", label: "KORBA", parentValue: "22" },
	{ value: "384", label: "KOREA", parentValue: "22" },
	{ value: "385", label: "MAHASAMUND", parentValue: "22" },
	{ value: "386", label: "RAIGARH", parentValue: "22" },
	{ value: "387", label: "RAIPUR", parentValue: "22" },
	{ value: "388", label: "RAJNANDGAON", parentValue: "22" },
	{ value: "389", label: "SURGUJA", parentValue: "22" },
	{ value: "636", label: "BIJAPUR", parentValue: "22" },
	{ value: "637", label: "NARAYANPUR", parentValue: "22" },
	{ value: "642", label: "SUKMA", parentValue: "22" },
	{ value: "643", label: "KONDAGAON", parentValue: "22" },
	{ value: "644", label: "BALODA BAZAR", parentValue: "22" },
	{ value: "645", label: "GARIYABAND", parentValue: "22" },
	{ value: "646", label: "BALOD", parentValue: "22" },
	{ value: "647", label: "MUNGELI", parentValue: "22" },
	{ value: "648", label: "SURAJPUR", parentValue: "22" },
	{ value: "649", label: "BALRAMPUR", parentValue: "22" },
	{ value: "650", label: "BEMETARA", parentValue: "22" },
	{ value: "390", label: "ANUPPUR", parentValue: "23" },
	{ value: "391", label: "ASHOKNAGAR", parentValue: "23" },
	{ value: "392", label: "BALAGHAT", parentValue: "23" },
	{ value: "393", label: "BARWANI", parentValue: "23" },
	{ value: "394", label: "BETUL", parentValue: "23" },
	{ value: "395", label: "BHIND", parentValue: "23" },
	{ value: "396", label: "BHOPAL", parentValue: "23" },
	{ value: "397", label: "BURHANPUR", parentValue: "23" },
	{ value: "398", label: "CHHATARPUR", parentValue: "23" },
	{ value: "399", label: "CHHINDWARA", parentValue: "23" },
	{ value: "400", label: "DAMOH", parentValue: "23" },
	{ value: "401", label: "DATIA", parentValue: "23" },
	{ value: "402", label: "DEWAS", parentValue: "23" },
	{ value: "403", label: "DHAR", parentValue: "23" },
	{ value: "404", label: "DINDORI", parentValue: "23" },
	{ value: "405", label: "EAST NIMAR", parentValue: "23" },
	{ value: "406", label: "GUNA", parentValue: "23" },
	{ value: "407", label: "GWALIOR", parentValue: "23" },
	{ value: "408", label: "HARDA", parentValue: "23" },
	{ value: "409", label: "HOSHANGABAD", parentValue: "23" },
	{ value: "410", label: "INDORE", parentValue: "23" },
	{ value: "411", label: "JABALPUR", parentValue: "23" },
	{ value: "412", label: "JHABUA", parentValue: "23" },
	{ value: "413", label: "KATNI", parentValue: "23" },
	{ value: "414", label: "KHARGONE", parentValue: "23" },
	{ value: "415", label: "MANDLA", parentValue: "23" },
	{ value: "416", label: "MANDSAUR", parentValue: "23" },
	{ value: "417", label: "MORENA", parentValue: "23" },
	{ value: "418", label: "NARSINGHPUR", parentValue: "23" },
	{ value: "419", label: "NEEMUCH", parentValue: "23" },
	{ value: "420", label: "PANNA", parentValue: "23" },
	{ value: "421", label: "RAISEN", parentValue: "23" },
	{ value: "422", label: "RAJGARH", parentValue: "23" },
	{ value: "423", label: "RATLAM", parentValue: "23" },
	{ value: "424", label: "REWA", parentValue: "23" },
	{ value: "425", label: "SAGAR", parentValue: "23" },
	{ value: "426", label: "SATNA", parentValue: "23" },
	{ value: "427", label: "SEHORE", parentValue: "23" },
	{ value: "428", label: "SEONI", parentValue: "23" },
	{ value: "429", label: "SHAHDOL", parentValue: "23" },
	{ value: "430", label: "SHAJAPUR", parentValue: "23" },
	{ value: "431", label: "SHEOPUR", parentValue: "23" },
	{ value: "432", label: "SHIVPURI", parentValue: "23" },
	{ value: "433", label: "SIDHI", parentValue: "23" },
	{ value: "434", label: "TIKAMGARH", parentValue: "23" },
	{ value: "435", label: "UJJAIN", parentValue: "23" },
	{ value: "436", label: "UMARIA", parentValue: "23" },
	{ value: "437", label: "VIDISHA", parentValue: "23" },
	{ value: "638", label: "SINGRAULI", parentValue: "23" },
	{ value: "639", label: "ALIRAJPUR", parentValue: "23" },
	{ value: "667", label: "AGAR MALWA", parentValue: "23" },
	{ value: "722", label: "Niwari", parentValue: "23" },
	{ value: "438", label: "AHMADABAD", parentValue: "24" },
	{ value: "439", label: "AMRELI", parentValue: "24" },
	{ value: "440", label: "ANAND", parentValue: "24" },
	{ value: "441", label: "BANAS KANTHA", parentValue: "24" },
	{ value: "442", label: "BHARUCH", parentValue: "24" },
	{ value: "443", label: "BHAVNAGAR", parentValue: "24" },
	{ value: "444", label: "DANG", parentValue: "24" },
	{ value: "445", label: "DOHAD", parentValue: "24" },
	{ value: "446", label: "GANDHINAGAR", parentValue: "24" },
	{ value: "447", label: "JAMNAGAR", parentValue: "24" },
	{ value: "448", label: "JUNAGADH", parentValue: "24" },
	{ value: "449", label: "KACHCHH", parentValue: "24" },
	{ value: "450", label: "KHEDA", parentValue: "24" },
	{ value: "451", label: "MAHESANA", parentValue: "24" },
	{ value: "452", label: "NARMADA", parentValue: "24" },
	{ value: "453", label: "NAVSARI", parentValue: "24" },
	{ value: "454", label: "PANCH MAHALS", parentValue: "24" },
	{ value: "455", label: "PATAN", parentValue: "24" },
	{ value: "456", label: "PORBANDAR", parentValue: "24" },
	{ value: "457", label: "RAJKOT", parentValue: "24" },
	{ value: "458", label: "SABAR KANTHA", parentValue: "24" },
	{ value: "459", label: "SURAT", parentValue: "24" },
	{ value: "460", label: "SURENDRANAGAR", parentValue: "24" },
	{ value: "461", label: "VADODARA", parentValue: "24" },
	{ value: "462", label: "VALSAD", parentValue: "24" },
	{ value: "641", label: "TAPI", parentValue: "24" },
	{ value: "668", label: "CHHOTAUDEPUR", parentValue: "24" },
	{ value: "669", label: "Mahisagar", parentValue: "24" },
	{ value: "672", label: "ARVALLI", parentValue: "24" },
	{ value: "673", label: "MORBI", parentValue: "24" },
	{ value: "674", label: "DEVBHUMI DWARKA", parentValue: "24" },
	{ value: "675", label: "GIR SOMNATH", parentValue: "24" },
	{ value: "676", label: "BOTAD", parentValue: "24" },
	{ value: "463", label: "DAMAN", parentValue: "25" },
	{ value: "464", label: "DIU", parentValue: "25" },
	{ value: "465", label: "DADRA AND NAGAR HAVELI", parentValue: "26" },
	{ value: "466", label: "AHMEDNAGAR", parentValue: "27" },
	{ value: "467", label: "AKOLA", parentValue: "27" },
	{ value: "468", label: "AMRAVATI", parentValue: "27" },
	{ value: "469", label: "AURANGABAD", parentValue: "27" },
	{ value: "470", label: "BEED", parentValue: "27" },
	{ value: "471", label: "BHANDARA", parentValue: "27" },
	{ value: "472", label: "BULDHANA", parentValue: "27" },
	{ value: "473", label: "CHANDRAPUR", parentValue: "27" },
	{ value: "474", label: "DHULE", parentValue: "27" },
	{ value: "475", label: "GADCHIROLI", parentValue: "27" },
	{ value: "476", label: "GONDIA", parentValue: "27" },
	{ value: "477", label: "HINGOLI", parentValue: "27" },
	{ value: "478", label: "JALGAON", parentValue: "27" },
	{ value: "479", label: "JALNA", parentValue: "27" },
	{ value: "480", label: "KOLHAPUR", parentValue: "27" },
	{ value: "481", label: "LATUR", parentValue: "27" },
	{ value: "482", label: "MUMBAI", parentValue: "27" },
	{ value: "483", label: "MUMBAI SUBURBAN", parentValue: "27" },
	{ value: "484", label: "NAGPUR", parentValue: "27" },
	{ value: "485", label: "NANDED", parentValue: "27" },
	{ value: "486", label: "NANDURBAR", parentValue: "27" },
	{ value: "487", label: "NASHIK", parentValue: "27" },
	{ value: "488", label: "OSMANABAD", parentValue: "27" },
	{ value: "489", label: "PARBHANI", parentValue: "27" },
	{ value: "490", label: "PUNE", parentValue: "27" },
	{ value: "491", label: "RAIGAD", parentValue: "27" },
	{ value: "492", label: "RATNAGIRI", parentValue: "27" },
	{ value: "493", label: "SANGLI", parentValue: "27" },
	{ value: "494", label: "SATARA", parentValue: "27" },
	{ value: "495", label: "SINDHUDURG", parentValue: "27" },
	{ value: "496", label: "SOLAPUR", parentValue: "27" },
	{ value: "497", label: "THANE", parentValue: "27" },
	{ value: "498", label: "WARDHA", parentValue: "27" },
	{ value: "499", label: "WASHIM", parentValue: "27" },
	{ value: "500", label: "YAVATMAL", parentValue: "27" },
	{ value: "665", label: "PALGHAR", parentValue: "27" },
	{ value: "502", label: "ANANTAPUR", parentValue: "37" },
	{ value: "503", label: "CHITTOOR", parentValue: "37" },
	{ value: "504", label: "Y.S.R.", parentValue: "37" },
	{ value: "505", label: "EAST GODAVARI", parentValue: "37" },
	{ value: "506", label: "GUNTUR", parentValue: "37" },
	{ value: "510", label: "KRISHNA", parentValue: "37" },
	{ value: "511", label: "KURNOOL", parentValue: "37" },
	{ value: "515", label: "SPSR NELLORE", parentValue: "37" },
	{ value: "517", label: "PRAKASAM", parentValue: "37" },
	{ value: "519", label: "SRIKAKULAM", parentValue: "37" },
	{ value: "520", label: "VISAKHAPATANAM", parentValue: "37" },
	{ value: "521", label: "VIZIANAGARAM", parentValue: "37" },
	{ value: "523", label: "WEST GODAVARI", parentValue: "37" },
	{ value: "524", label: "BAGALKOTE", parentValue: "29" },
	{ value: "525", label: "BENGALURU URBAN", parentValue: "29" },
	{ value: "526", label: "BENGALURU RURAL", parentValue: "29" },
	{ value: "527", label: "BELAGAVI", parentValue: "29" },
	{ value: "528", label: "BALLARI", parentValue: "29" },
	{ value: "529", label: "BIDAR", parentValue: "29" },
	{ value: "530", label: "VIJAYAPURA", parentValue: "29" },
	{ value: "531", label: "CHAMARAJANAGARA", parentValue: "29" },
	{ value: "532", label: "CHIKKAMAGALURU", parentValue: "29" },
	{ value: "533", label: "CHITRADURGA", parentValue: "29" },
	{ value: "534", label: "DAKSHINA KANNADA", parentValue: "29" },
	{ value: "535", label: "DAVANGERE", parentValue: "29" },
	{ value: "536", label: "DHARWAD", parentValue: "29" },
	{ value: "537", label: "GADAG", parentValue: "29" },
	{ value: "538", label: "KALABURAGI", parentValue: "29" },
	{ value: "539", label: "HASSAN", parentValue: "29" },
	{ value: "540", label: "HAVERI", parentValue: "29" },
	{ value: "541", label: "KODAGU", parentValue: "29" },
	{ value: "542", label: "KOLAR", parentValue: "29" },
	{ value: "543", label: "KOPPAL", parentValue: "29" },
	{ value: "544", label: "MANDYA", parentValue: "29" },
	{ value: "545", label: "MYSURU", parentValue: "29" },
	{ value: "546", label: "RAICHUR", parentValue: "29" },
	{ value: "547", label: "SHIVAMOGGA", parentValue: "29" },
	{ value: "548", label: "TUMAKURU", parentValue: "29" },
	{ value: "549", label: "UDUPI", parentValue: "29" },
	{ value: "550", label: "UTTARA KANNADA", parentValue: "29" },
	{ value: "630", label: "CHIKKABALLAPURA", parentValue: "29" },
	{ value: "631", label: "RAMANAGARA", parentValue: "29" },
	{ value: "635", label: "YADGIR", parentValue: "29" },
	{ value: "551", label: "NORTH GOA", parentValue: "30" },
	{ value: "552", label: "SOUTH GOA", parentValue: "30" },
	{ value: "553", label: "LAKSHADWEEP DISTRICT", parentValue: "31" },
	{ value: "554", label: "ALAPPUZHA", parentValue: "32" },
	{ value: "555", label: "ERNAKULAM", parentValue: "32" },
	{ value: "556", label: "IDUKKI", parentValue: "32" },
	{ value: "557", label: "KANNUR", parentValue: "32" },
	{ value: "558", label: "KASARAGOD", parentValue: "32" },
	{ value: "559", label: "KOLLAM", parentValue: "32" },
	{ value: "560", label: "KOTTAYAM", parentValue: "32" },
	{ value: "561", label: "KOZHIKODE", parentValue: "32" },
	{ value: "562", label: "MALAPPURAM", parentValue: "32" },
	{ value: "563", label: "PALAKKAD", parentValue: "32" },
	{ value: "564", label: "PATHANAMTHITTA", parentValue: "32" },
	{ value: "565", label: "THIRUVANANTHAPURAM", parentValue: "32" },
	{ value: "566", label: "THRISSUR", parentValue: "32" },
	{ value: "567", label: "WAYANAD", parentValue: "32" },
	{ value: "568", label: "CHENNAI", parentValue: "33" },
	{ value: "569", label: "COIMBATORE", parentValue: "33" },
	{ value: "570", label: "CUDDALORE", parentValue: "33" },
	{ value: "571", label: "DHARMAPURI", parentValue: "33" },
	{ value: "572", label: "DINDIGUL", parentValue: "33" },
	{ value: "573", label: "ERODE", parentValue: "33" },
	{ value: "574", label: "KANCHIPURAM", parentValue: "33" },
	{ value: "575", label: "KANNIYAKUMARI", parentValue: "33" },
	{ value: "576", label: "KARUR", parentValue: "33" },
	{ value: "577", label: "KRISHNAGIRI", parentValue: "33" },
	{ value: "578", label: "MADURAI", parentValue: "33" },
	{ value: "579", label: "NAGAPATTINAM", parentValue: "33" },
	{ value: "580", label: "NAMAKKAL", parentValue: "33" },
	{ value: "581", label: "PERAMBALUR", parentValue: "33" },
	{ value: "582", label: "PUDUKKOTTAI", parentValue: "33" },
	{ value: "583", label: "RAMANATHAPURAM", parentValue: "33" },
	{ value: "584", label: "SALEM", parentValue: "33" },
	{ value: "585", label: "SIVAGANGA", parentValue: "33" },
	{ value: "586", label: "THANJAVUR", parentValue: "33" },
	{ value: "587", label: "THE NILGIRIS", parentValue: "33" },
	{ value: "588", label: "THENI", parentValue: "33" },
	{ value: "589", label: "THIRUVALLUR", parentValue: "33" },
	{ value: "590", label: "THIRUVARUR", parentValue: "33" },
	{ value: "591", label: "TIRUCHIRAPPALLI", parentValue: "33" },
	{ value: "592", label: "TIRUNELVELI", parentValue: "33" },
	{ value: "593", label: "TIRUVANNAMALAI", parentValue: "33" },
	{ value: "594", label: "TUTICORIN", parentValue: "33" },
	{ value: "595", label: "VELLORE", parentValue: "33" },
	{ value: "596", label: "VILLUPURAM", parentValue: "33" },
	{ value: "597", label: "VIRUDHUNAGAR", parentValue: "33" },
	{ value: "610", label: "Ariyalur", parentValue: "33" },
	{ value: "634", label: "TIRUPPUR", parentValue: "33" },
	{ value: "598", label: "KARAIKAL", parentValue: "34" },
	{ value: "599", label: "MAHE", parentValue: "34" },
	{ value: "600", label: "PONDICHERRY", parentValue: "34" },
	{ value: "601", label: "YANAM", parentValue: "34" },
	{ value: "602", label: "SOUTH ANDAMANS", parentValue: "35" },
	{ value: "603", label: "NICOBARS", parentValue: "35" },
	{ value: "632", label: "NORTH AND MIDDLE ANDAMAN", parentValue: "35" },
	{ value: "501", label: "ADILABAD", parentValue: "36" },
	{ value: "507", label: "HYDERABAD", parentValue: "36" },
	{ value: "508", label: "KARIMNAGAR", parentValue: "36" },
	{ value: "509", label: "KHAMMAM", parentValue: "36" },
	{ value: "512", label: "MAHABUBNAGAR", parentValue: "36" },
	{ value: "513", label: "MEDAK", parentValue: "36" },
	{ value: "514", label: "NALGONDA", parentValue: "36" },
	{ value: "516", label: "NIZAMABAD", parentValue: "36" },
	{ value: "518", label: "RANGA REDDY", parentValue: "36" },
	{ value: "522", label: "WARANGAL RURAL", parentValue: "36" },
	{ value: "680", label: "Nirmal", parentValue: "36" },
	{ value: "681", label: "Jagitial", parentValue: "36" },
	{ value: "682", label: "PEDDAPALLI", parentValue: "36" },
	{ value: "683", label: "RAJANNA SIRCILLA", parentValue: "36" },
	{ value: "684", label: "MANCHERIAL", parentValue: "36" },
	{ value: "685", label: "KAMAREDDY", parentValue: "36" },
	{ value: "686", label: "WARANGAL URBAN", parentValue: "36" },
	{ value: "687", label: "JAYASHANKAR BHUPALAPALLY", parentValue: "36" },
	{ value: "688", label: "MAHABUBABAD", parentValue: "36" },
	{ value: "689", label: "JANGOAN", parentValue: "36" },
	{ value: "690", label: "BHADRADRI KOTHAGUDEM", parentValue: "36" },
	{ value: "691", label: "SANGAREDDY", parentValue: "36" },
	{ value: "692", label: "SIDDIPET", parentValue: "36" },
	{ value: "693", label: "WANAPARTHY", parentValue: "36" },
	{ value: "694", label: "NAGARKURNOOL", parentValue: "36" },
	{ value: "695", label: "JOGULAMBA GADWAL", parentValue: "36" },
	{ value: "696", label: "SURYAPET", parentValue: "36" },
	{ value: "697", label: "YADADRI BHUVANAGIRI", parentValue: "36" },
	{ value: "698", label: "VIKARABAD", parentValue: "36" },
	{ value: "699", label: "KUMURAM BHEEM ASIFABAD", parentValue: "36" },
	{ value: "700", label: "MEDCHAL MALKAJGIRI", parentValue: "36" },
	{ value: "720", label: "Mulugu", parentValue: "36" },
	{ value: "721", label: "Narayanpet", parentValue: "36" },
	{ value: "06", label: "KARGIL", parentValue: "38" },
	{ value: "09", label: "LEH LADAKH", parentValue: "38" }
]);
